use nestweaver_store::GraphStore;

/// Generate AGENTS.md content from the indexed graph.
///
/// Returns a markdown string that summarizes the indexed repositories,
/// architectural skeleton, knowledge vaults, and available MCP tools.
/// Intended to be written to `AGENTS.md` at the workspace root so AI
/// agents pick it up automatically at session start.
pub fn generate_guide(store: &GraphStore) -> Result<String, anyhow::Error> {
    let mut out = String::new();

    out.push_str("# Codebase Intelligence Guide\n\n");
    out.push_str("> Auto-generated by NestWeaver. Do not edit manually.\n\n");

    // Section 1: Repositories
    out.push_str("## Repositories\n\n");
    let repos = store.list_repos(None).unwrap_or_default();
    if repos.is_empty() {
        out.push_str("No repositories indexed yet.\n\n");
    } else {
        for repo in &repos {
            let sha_short = if repo.indexed_sha.len() >= 8 {
                &repo.indexed_sha[..8]
            } else {
                &repo.indexed_sha
            };
            out.push_str(&format!("- `{}` (sha: {})\n", repo.url, sha_short));
        }
        out.push('\n');
    }

    // Section 2: Architecture overview (repo map)
    out.push_str("## Architecture\n\n");
    match crate::query::generate_repo_map(store, 2000) {
        Ok(map) => {
            out.push_str("```\n");
            out.push_str(&map);
            out.push_str("\n```\n\n");
        }
        Err(_) => {
            out.push_str("No symbols indexed yet.\n\n");
        }
    }

    // Section 3: Knowledge vaults
    let vaults = store.list_vaults(None).unwrap_or_default();
    if !vaults.is_empty() {
        out.push_str("## Knowledge Vaults\n\n");
        for vault in &vaults {
            let notes = store.list_notes(Some(&vault.uid)).unwrap_or_default();
            out.push_str(&format!("### {} ({} notes)\n\n", vault.name, notes.len()));
            for note in notes.iter().take(20) {
                out.push_str(&format!("- {}\n", note.title));
            }
            if notes.len() > 20 {
                out.push_str(&format!("- ... and {} more\n", notes.len() - 20));
            }
            out.push('\n');
        }
    }

    // Section 4: Available tools
    out.push_str("## NestWeaver Tools\n\n");
    out.push_str("This codebase is indexed by NestWeaver. Available MCP tools:\n\n");
    out.push_str("| Tool | Use when |\n");
    out.push_str("|------|----------|\n");
    out.push_str("| `brain_context` | Exploring unfamiliar code — seeds from symbols, files, or note titles |\n");
    out.push_str("| `brain_search` | Finding symbols or notes by keyword |\n");
    out.push_str("| `note_get` | Reading a vault note's full content |\n");
    out.push_str("| `backlinks` | Finding what links TO a note |\n");
    out.push_str("| `brain_impact` | Checking blast radius before modifying a function |\n");
    out.push_str("| `cross_repo_contracts` | Finding cross-service symbol relationships |\n");
    out.push_str("| `brain_status` | Checking what's indexed |\n");
    out.push('\n');

    // Section 5: CLI + Web
    out.push_str("## Quick Start\n\n");
    out.push_str("```bash\n");
    out.push_str("# Re-index (incremental — only changed files)\n");
    out.push_str("nestweaver index --repo .\n\n");
    out.push_str("# Search for a symbol\n");
    out.push_str("nestweaver search <name>\n\n");
    out.push_str("# Get context for a function\n");
    out.push_str("nestweaver context <name>\n\n");
    out.push_str("# Launch the web UI\n");
    out.push_str("nestweaver ui\n");
    out.push_str("```\n");

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_guide_produces_valid_markdown() {
        let store = nestweaver_store::GraphStore::in_memory().unwrap();
        let guide = generate_guide(&store).unwrap();
        assert!(guide.contains("# Codebase Intelligence Guide"));
        assert!(guide.contains("## NestWeaver Tools"));
        assert!(guide.contains("brain_context"));
    }
}
