use nestweaver_store::GraphStore;

use crate::config::InstanceConfig;

/// Generate AGENTS.md content from the indexed graph.
///
/// Returns a markdown string that summarizes the indexed repositories,
/// architectural skeleton, knowledge vaults, and available MCP tools.
/// Intended to be written to `AGENTS.md` at the workspace root so AI
/// agents pick it up automatically at session start.
///
/// Pass an optional `InstanceConfig` to include declared `[[features]]` and
/// `[[links]]` sections in the output. When `None`, those sections are omitted
/// but the cross-repo edges discovered in the graph are still shown.
pub fn generate_guide(
    store: &GraphStore,
    config: Option<&InstanceConfig>,
) -> Result<String, anyhow::Error> {
    let mut out = String::new();

    out.push_str("# Codebase Intelligence Guide\n\n");
    out.push_str("> Auto-generated by NestWeaver. Do not edit manually.\n\n");

    // Section 1: Repositories
    out.push_str("## Repositories\n\n");
    let repos = store.list_repos(None).unwrap_or_default();
    if repos.is_empty() {
        out.push_str("No repositories indexed yet.\n\n");
    } else {
        for repo in &repos {
            let sha_short = if repo.indexed_sha.len() >= 8 {
                &repo.indexed_sha[..8]
            } else {
                &repo.indexed_sha
            };
            out.push_str(&format!("- `{}` (sha: {})\n", repo.url, sha_short));
        }
        out.push('\n');
    }

    // Section 2: Architecture overview (repo map)
    out.push_str("## Architecture\n\n");
    match crate::query::generate_repo_map(store, 2000) {
        Ok(map) => {
            out.push_str("```\n");
            out.push_str(&map);
            out.push_str("\n```\n\n");
        }
        Err(_) => {
            out.push_str("No symbols indexed yet.\n\n");
        }
    }

    // Section 3: Cross-repo links discovered in the graph
    let cross_links = store.list_all_cross_repo_links(50).unwrap_or_default();
    if !cross_links.is_empty() {
        // Build a repo-uid → short name map from indexed repos.
        let repo_name: std::collections::HashMap<String, String> = repos
            .iter()
            .map(|r| {
                // Derive a short name: last path component of the URL.
                let short = r
                    .url
                    .trim_end_matches('/')
                    .rsplit('/')
                    .next()
                    .unwrap_or(&r.url)
                    .trim_end_matches(".git")
                    .to_string();
                (r.uid.clone(), short)
            })
            .collect();

        // Group by (source_repo_uid, target_repo_uid, link_type) to collect shared symbols.
        use std::collections::BTreeMap;
        let mut groups: BTreeMap<(String, String, String), Vec<String>> = BTreeMap::new();
        for link in &cross_links {
            let src_repo = link
                .source_repo_uid
                .as_deref()
                .map(|u| repo_name.get(u).cloned().unwrap_or_else(|| u.to_string()))
                .unwrap_or_else(|| "?".to_string());
            let tgt_repo = link
                .target_repo_uid
                .as_deref()
                .map(|u| repo_name.get(u).cloned().unwrap_or_else(|| u.to_string()))
                .unwrap_or_else(|| "?".to_string());
            groups
                .entry((src_repo, tgt_repo, link.link_type.clone()))
                .or_default()
                .push(link.source_name.clone());
        }

        out.push_str("## Cross-Repository Links\n\n");
        out.push_str("| From | To | Type | Shared Symbols |\n");
        out.push_str("|------|----|------|---------------|\n");
        for ((src, tgt, ltype), mut symbols) in groups {
            symbols.sort();
            symbols.dedup();
            let syms_preview: Vec<&str> = symbols.iter().take(5).map(|s| s.as_str()).collect();
            let syms_str = if symbols.len() > 5 {
                format!("{}, … (+{})", syms_preview.join(", "), symbols.len() - 5)
            } else {
                syms_preview.join(", ")
            };
            out.push_str(&format!("| {src} | {tgt} | {ltype} | {syms_str} |\n"));
        }
        out.push('\n');
    }

    // Section 4: Declared links from instance config
    if let Some(cfg) = config {
        if let Some(links) = &cfg.links
            && !links.is_empty()
        {
            out.push_str("## Declared Links\n\n");
            out.push_str("| From | To | Type | Description |\n");
            out.push_str("|------|----|------|-------------|\n");
            for link in links {
                let desc = link.description.as_deref().unwrap_or("");
                out.push_str(&format!(
                    "| {} | {} | {} | {} |\n",
                    link.from, link.to, link.link_type, desc
                ));
            }
            out.push('\n');
        }

        // Section 5: Feature bundles from instance config
        if let Some(features) = &cfg.features
            && !features.is_empty()
        {
            out.push_str("## Feature Bundles\n\n");
            for feat in features {
                out.push_str(&format!("### {}\n\n", feat.name));
                if let Some(desc) = &feat.description {
                    out.push_str(&format!("> {desc}\n\n"));
                }
                out.push_str(&format!("- **Repos:** {}\n", feat.repos.join(", ")));
                out.push_str(&format!(
                    "- **Entry Points:** {}\n",
                    feat.entry_points.join(", ")
                ));
                out.push('\n');
            }
        }
    }

    // Section 6: Projects
    let projects = store.list_projects().unwrap_or_default();
    let empty_projects: Vec<crate::config::ProjectConfig> = Vec::new();
    let config_projects: &[crate::config::ProjectConfig] = config
        .map(|c| c.projects.as_slice())
        .unwrap_or(&empty_projects);
    // Merge: start from store projects, then add any config entries not already present.
    let mut all_project_names: Vec<String> = projects.iter().map(|p| p.name.clone()).collect();
    for cp in config_projects {
        if !all_project_names
            .iter()
            .any(|n| n.eq_ignore_ascii_case(&cp.name))
        {
            all_project_names.push(cp.name.clone());
        }
    }
    if !all_project_names.is_empty() {
        out.push_str("## Projects\n\n");
        for project_name in &all_project_names {
            // Find the store project (may be None if only in config).
            let store_project = projects
                .iter()
                .find(|p| p.name.eq_ignore_ascii_case(project_name));
            // Find the config project entry (if any).
            let cfg_project = config_projects
                .iter()
                .find(|cp| cp.name.eq_ignore_ascii_case(project_name));

            out.push_str(&format!("### {project_name}\n\n"));

            // Description from config.
            if let Some(desc) = cfg_project.and_then(|cp| cp.description.as_deref()) {
                out.push_str(&format!("- **Description:** {desc}\n"));
            } else if let Some(desc) = store_project.and_then(|p| p.summary.as_deref()) {
                out.push_str(&format!("- **Description:** {desc}\n"));
            }

            // Aliases from config.
            if let Some(cp) = cfg_project
                && !cp.aliases.is_empty()
            {
                out.push_str(&format!("- **Aliases:** {}\n", cp.aliases.join(", ")));
            }

            // Vault folder from config.
            if let Some(folder) = cfg_project.and_then(|cp| cp.vault_folder.as_deref()) {
                out.push_str(&format!("- **Vault folder:** {folder}\n"));
            }

            // Repos from config.
            if let Some(cp) = cfg_project
                && !cp.repos.is_empty()
            {
                out.push_str(&format!("- **Repos:** {}\n", cp.repos.join(", ")));
            }

            // Component count from store.
            if let Some(p) = store_project {
                let component_count = store
                    .list_project_component_uids(&p.uid)
                    .unwrap_or_default()
                    .len();
                if component_count > 0 {
                    out.push_str(&format!("- **Components:** {component_count}\n"));
                }
            }

            // External refs from config.
            if let Some(cp) = cfg_project
                && !cp.external_refs.is_empty()
            {
                let refs_str: Vec<String> = cp
                    .external_refs
                    .iter()
                    .map(|r| {
                        if let Some(ref_type) = &r.ref_type {
                            format!("{} ({})", r.label, ref_type)
                        } else {
                            r.label.clone()
                        }
                    })
                    .collect();
                out.push_str(&format!("- **External refs:** {}\n", refs_str.join(", ")));
            }

            // Recent activity: max(note.modified_at) from project notes.
            if let Some(p) = store_project {
                let note_uids = store.list_project_note_uids(&p.uid).unwrap_or_default();
                let recent: Option<String> = note_uids
                    .iter()
                    .filter_map(|uid| store.lookup_note(uid).ok())
                    .filter_map(|n| n.modified_at)
                    .max();
                if let Some(ts) = recent {
                    out.push_str(&format!("- **Recent activity:** {ts}\n"));
                }
            }

            out.push('\n');
        }
    }

    // Section 7: Knowledge vaults
    let vaults = store.list_vaults(None).unwrap_or_default();
    if !vaults.is_empty() {
        out.push_str("## Knowledge Vaults\n\n");
        for vault in &vaults {
            let notes = store.list_notes(Some(&vault.uid)).unwrap_or_default();
            out.push_str(&format!("### {} ({} notes)\n\n", vault.name, notes.len()));
            for note in notes.iter().take(20) {
                out.push_str(&format!("- {}\n", note.title));
            }
            if notes.len() > 20 {
                out.push_str(&format!("- ... and {} more\n", notes.len() - 20));
            }
            out.push('\n');
        }
    }

    // Section 8: Available tools
    out.push_str("## NestWeaver Tools\n\n");
    out.push_str("This codebase is indexed by NestWeaver. Available MCP tools:\n\n");
    out.push_str("| Tool | Use when |\n");
    out.push_str("|------|----------|\n");
    out.push_str("| `brain_context` | Exploring unfamiliar code — seeds from symbols, files, or note titles |\n");
    out.push_str("| `brain_search` | Finding symbols or notes by keyword |\n");
    out.push_str("| `note_get` | Reading a vault note's full content |\n");
    out.push_str("| `backlinks` | Finding what links TO a note |\n");
    out.push_str("| `brain_impact` | Checking blast radius before modifying a function |\n");
    out.push_str("| `cross_repo_contracts` | Finding cross-service symbol relationships |\n");
    out.push_str("| `brain_status` | Checking what's indexed |\n");
    out.push('\n');

    // Section 9: CLI + Web
    out.push_str("## Quick Start\n\n");
    out.push_str("```bash\n");
    out.push_str("# Re-index (incremental — only changed files)\n");
    out.push_str("nestweaver index --repo .\n\n");
    out.push_str("# Search for a symbol\n");
    out.push_str("nestweaver search <name>\n\n");
    out.push_str("# Get context for a function\n");
    out.push_str("nestweaver context <name>\n\n");
    out.push_str("# Launch the web UI\n");
    out.push_str("nestweaver ui\n");
    out.push_str("```\n\n");

    // Section 10: Web UI
    out.push_str("## Web UI\n\n");
    out.push_str(
        "NestWeaver includes an interactive graph visualization accessible from a browser.\n\n",
    );
    out.push_str("```bash\n");
    out.push_str("nestweaver ui --db ./nestweaver.lbug --port 8080\n");
    out.push_str("nestweaver ui --db ./nestweaver.lbug --port 8080 --watch  # live re-indexing\n");
    out.push_str("```\n\n");
    out.push_str("Open `http://localhost:8080` after starting. Append `?engine=wasm` to the URL to run graph algorithms (PPR) client-side via WebAssembly — the browser downloads a MessagePack snapshot and executes queries locally with no server round-trips.\n\n");
    out.push_str("**API endpoints** (served by the running UI process):\n\n");
    out.push_str("| Endpoint | Description |\n");
    out.push_str("|----------|-------------|\n");
    out.push_str(
        "| `GET /api/v1/version` | `{\"graph_generation\": N, \"pagerank_generation\": N}` |\n",
    );
    out.push_str("| `GET /api/v1/snapshot.msgpack` | MessagePack-encoded graph (`X-Graph-Generation` header) |\n");
    out.push_str("| `GET /api/v1/events` | SSE stream: `graph:updated`, `pagerank:recomputed`, `full_refresh` |\n");
    out.push('\n');

    Ok(out)
}

/// Generate a SKILL.md conforming to the Agent Skills open standard.
///
/// Returns a skill document with YAML frontmatter (`name`, `description`)
/// and a markdown body that teaches an AI agent how to use NestWeaver
/// effectively: when to activate, which MCP tools to call, common
/// workflows, graph query patterns, and response interpretation.
///
/// The `description` field acts as a classifier prompt so the agent
/// activates this skill at the right time.
pub fn generate_skill(
    store: &GraphStore,
    config: Option<&InstanceConfig>,
) -> Result<String, anyhow::Error> {
    let mut out = String::new();

    // ── YAML frontmatter ─────────────────────────────────────────────────
    out.push_str("---\n");
    out.push_str("name: nestweaver\n");
    out.push_str("description: |\n");
    out.push_str(
        "  Use when exploring codebase structure, understanding dependencies, analyzing\n",
    );
    out.push_str(
        "  change impact, navigating architecture, or retrieving knowledge-vault notes.\n",
    );
    out.push_str("  Do NOT use for simple text search, file reading, or tasks unrelated to code\n");
    out.push_str("  structure and project knowledge.\n");
    out.push_str("---\n\n");

    // ── Trigger logic ────────────────────────────────────────────────────
    out.push_str("## When to activate\n\n");
    out.push_str("Activate this skill when the task involves:\n\n");
    out.push_str("- Understanding how a function, module, or file fits into the codebase\n");
    out.push_str("- Checking what will break before modifying a symbol (blast radius)\n");
    out.push_str("- Tracing call chains or execution flow from an entry point\n");
    out.push_str("- Navigating cross-repository dependencies or shared contracts\n");
    out.push_str("- Retrieving project knowledge from Obsidian vaults or markdown notes\n");
    out.push_str("- Getting a structural overview of the architecture\n");
    out.push_str("- Assessing risk of a set of changed files before commit\n\n");

    out.push_str("Do NOT activate when:\n\n");
    out.push_str("- The user just wants to read a specific file (use normal file reading)\n");
    out.push_str("- The task is plain text search with no structural intent (use grep/ripgrep)\n");
    out.push_str("- The question is about runtime behavior, logs, or deployment\n\n");

    // ── Vocabulary ───────────────────────────────────────────────────────
    out.push_str("## Key concepts\n\n");
    out.push_str("- **Seeds**: Starting points for a graph walk. Can be symbol names, note titles, tag names (with or without `#`), free-text terms, or UIDs (`sym:`, `note:`, `head:`, `sec:`, `tag:`).\n");
    out.push_str("- **PPR (Personalized PageRank)**: The ranking algorithm. Walks the code+notes graph from seeds and scores every reachable node by structural proximity. Higher rank = closer relationship to the seeds.\n");
    out.push_str("- **Context**: A token-budgeted, PPR-ranked list of symbols, notes, and sections relevant to given seeds. The primary retrieval primitive.\n");
    out.push_str(
        "- **Brain**: The unified graph combining code symbols and markdown vault notes.\n",
    );
    out.push_str("- **Vault**: An indexed collection of markdown notes (e.g. an Obsidian vault). Notes are linked to code via wikilinks and tags.\n");
    out.push_str("- **Confidence**: A 0.0\u{2013}1.0 score on edges indicating how certain the resolver is about a relationship (e.g. an import or call). 1.0 = definite, <0.5 = heuristic guess.\n");
    out.push_str("- **Token budget**: Approximate output cap in tokens (chars / 4). Controls how much context is returned.\n\n");

    // ── MCP tools ────────────────────────────────────────────────────────
    out.push_str("## Available MCP tools\n\n");

    out.push_str("### Core retrieval\n\n");
    out.push_str("| Tool | Purpose | Key parameters |\n");
    out.push_str("|------|---------|----------------|\n");
    out.push_str("| `brain_context` | PPR-ranked context from seeds. **Call this first** for any structural question. | `seeds` (required), `token_budget`, `kinds`, `repos`, `vaults`, `tags`, `since`, `recency_weight` |\n");
    out.push_str("| `brain_search` | BM25 full-text search across notes, headings, sections, and tags. Use for keyword lookup. | `query`, `limit` |\n");
    out.push_str("| `project_context` | PPR-ranked context scoped to a named project and its components. | `project`, `token_budget`, `kinds`, `include_components` |\n");
    out.push_str("| `note_get` | Full markdown body of a specific note, with frontmatter and outline. | `uid` or `title`, `sections`, `include_body` |\n");
    out.push_str(
        "| `backlinks` | All notes that wikilink TO a target note. | `uid` or `title` |\n\n",
    );

    out.push_str("### Analysis\n\n");
    out.push_str("| Tool | Purpose | Key parameters |\n");
    out.push_str("|------|---------|----------------|\n");
    out.push_str("| `brain_impact` | Blast radius: all symbols that call/import/extend the target, grouped by depth. | `symbol`, `depth` |\n");
    out.push_str("| `flow_trace` | Forward call chain from a symbol (what it calls, transitively). | `symbol`, `depth` |\n");
    out.push_str("| `detect_changes` | Risk assessment for a list of changed files. Maps files to affected flows. | `files` |\n");
    out.push_str("| `cross_repo_contracts` | Symbols shared across repositories with confidence scores. | `symbol` |\n");
    out.push_str("| `clusters` | Functional communities detected by the Leiden algorithm. | `min_size`, `repo` |\n\n");

    out.push_str("### Status and maintenance\n\n");
    out.push_str("| Tool | Purpose |\n");
    out.push_str("|------|---------|\n");
    out.push_str(
        "| `brain_status` | Counts of vaults, notes, symbols, repos. Call to verify indexing. |\n",
    );
    out.push_str("| `stale_check` | Compare indexed SHA to current git HEAD. Shows if re-indexing is needed. |\n");
    out.push_str("| `brain_diff` | Files and symbols changed since a given SHA. Useful before code review. |\n");
    out.push_str(
        "| `brain_guide` | Auto-generated architecture overview of the indexed codebase. |\n",
    );
    out.push_str(
        "| `brain_add_source` | Index a new repo or vault at runtime. Pass an absolute path. |\n\n",
    );

    out.push_str("### Extensions\n\n");
    out.push_str("| Tool | Purpose |\n");
    out.push_str("|------|---------|\n");
    out.push_str("| `set_extension` | Attach custom metadata (e.g. `team_owner`, `deprecated`) to any node. |\n");
    out.push_str(
        "| `query_extensions` | Find nodes with a specific extension property value. |\n\n",
    );

    // ── Workflows ────────────────────────────────────────────────────────
    out.push_str("## Common workflows\n\n");

    out.push_str("### Understanding a function\n\n");
    out.push_str("1. `brain_context` with the function name as a seed. Review the ranked list of related symbols and notes.\n");
    out.push_str(
        "2. If you need the full call chain forward, use `flow_trace` on the same symbol.\n",
    );
    out.push_str("3. If you need to know what depends on it (callers), use `brain_impact`.\n\n");

    out.push_str("### Starting work on a task\n\n");
    out.push_str("1. `brain_context` with task-related keywords as seeds (e.g. `[\"authentication\", \"login\"]`). This returns the most structurally relevant symbols and notes.\n");
    out.push_str("2. If a project exists for this area, use `project_context` instead for project-scoped results.\n");
    out.push_str("3. Drill into specific notes with `note_get` when `brain_context` surfaces a relevant title.\n\n");

    out.push_str("### Before modifying code\n\n");
    out.push_str(
        "1. `brain_impact` on the symbol you plan to change. Check the depth-grouped callers.\n",
    );
    out.push_str("2. `detect_changes` with the list of files you expect to modify. Review the risk assessment.\n");
    out.push_str("3. If cross-repo, also call `cross_repo_contracts` to see if other services share the symbol.\n\n");

    out.push_str("### Exploring architecture\n\n");
    out.push_str("1. `brain_guide` for the full architecture overview.\n");
    out.push_str("2. `clusters` to see functional communities of tightly-connected symbols.\n");
    out.push_str("3. `brain_context` with broad seeds (module names, directory prefixes) for targeted exploration.\n\n");

    out.push_str("### Working with vault notes\n\n");
    out.push_str("1. `brain_search` with keywords to find relevant notes.\n");
    out.push_str("2. `note_get` to read the full body of a matched note.\n");
    out.push_str("3. `backlinks` to discover what links to a specific note.\n");
    out.push_str("4. Use `since` or `recency_weight` parameters on `brain_context` to prioritize recent notes.\n\n");

    // ── Query patterns ───────────────────────────────────────────────────
    out.push_str("## Graph query patterns\n\n");

    out.push_str("### Seeding context effectively\n\n");
    out.push_str(
        "- **Symbol name**: `seeds: [\"handleLogin\"]` — best for function-level exploration\n",
    );
    out.push_str("- **Multiple seeds**: `seeds: [\"auth\", \"session\", \"token\"]` — broader topic exploration; PPR walks from all seeds simultaneously\n");
    out.push_str("- **File path**: `seeds: [\"src/auth/handler.rs\"]` — all symbols in that file become seeds\n");
    out.push_str("- **Note title**: `seeds: [\"Architecture Decision Records\"]` — anchor on vault knowledge\n");
    out.push_str("- **Tag**: `seeds: [\"#deprecated\"]` — all nodes with that tag\n");
    out.push_str("- **UID**: `seeds: [\"sym:abc123\"]` — precise node targeting when you have a UID from a previous call\n\n");

    out.push_str("### Filtering results\n\n");
    out.push_str("- `kinds: [\"Symbol\"]` — code only, no notes\n");
    out.push_str("- `kinds: [\"Note\", \"Section\"]` — notes only, no code\n");
    out.push_str("- `repos: [\"backend\"]` — restrict to one repo\n");
    out.push_str("- `path_prefix: \"src/auth/\"` — restrict to a directory\n");
    out.push_str(
        "- `tags: [\"api\"]` / `exclude_tags: [\"draft\"]` — tag-based filtering on notes\n\n",
    );

    out.push_str("### Tuning retrieval\n\n");
    out.push_str("- Increase `token_budget` (default 2000) for broader context\n");
    out.push_str("- Adjust `weight_ppr` / `weight_bm25` to balance structural vs. textual relevance (defaults: 0.7 / 0.3)\n");
    out.push_str("- Set `recency_weight: 0.7` to boost recently-modified notes\n");
    out.push_str("- Use `since: \"2026-01-01T00:00:00Z\"` to filter out old notes\n\n");

    // ── Interpreting results ─────────────────────────────────────────────
    out.push_str("## Interpreting results\n\n");

    out.push_str("### PPR rankings in brain_context\n\n");
    out.push_str("Results are ordered by PPR score (highest first). The score reflects structural proximity to your seeds in the code+notes graph:\n\n");
    out.push_str("- **Top results** (highest PPR): Directly connected to your seeds — immediate callers, callees, or same-file symbols\n");
    out.push_str("- **Mid-range results**: Two or three hops away — used by the same module or referenced in related notes\n");
    out.push_str("- **Tail results**: Distant but still reachable — broader context that may or may not be relevant\n\n");

    out.push_str("### Confidence scores\n\n");
    out.push_str("Edges carry a confidence value from 0.0 to 1.0:\n\n");
    out.push_str("- **1.0**: Definite relationship (e.g. explicit import, direct function call parsed from AST)\n");
    out.push_str("- **0.7\u{2013}0.9**: High confidence (e.g. resolved cross-file reference with matching signature)\n");
    out.push_str("- **0.3\u{2013}0.6**: Heuristic match (e.g. name-based resolution without full type information)\n");
    out.push_str("- **<0.3**: Speculative (e.g. substring match on symbol names across repos)\n\n");

    out.push_str("### Impact depth groups\n\n");
    out.push_str("In `brain_impact` results, symbols are grouped by depth:\n\n");
    out.push_str("- **Depth 1**: Direct callers/dependents — these will definitely be affected\n");
    out.push_str("- **Depth 2**: Callers of callers — likely affected, review recommended\n");
    out.push_str("- **Depth 3+**: Transitive dependents — possibly affected, check if the change propagates\n\n");

    // ── Indexed codebase ─────────────────────────────────────────────────
    out.push_str("## Indexed codebase\n\n");

    let repos = store.list_repos(None).unwrap_or_default();
    if repos.is_empty() {
        out.push_str("No repositories indexed yet.\n\n");
    } else {
        for repo in &repos {
            let sha_short = if repo.indexed_sha.len() >= 8 {
                &repo.indexed_sha[..8]
            } else {
                &repo.indexed_sha
            };
            out.push_str(&format!("- `{}` (sha: {})\n", repo.url, sha_short));
        }
        out.push('\n');
    }

    // Vaults
    let vaults = store.list_vaults(None).unwrap_or_default();
    if !vaults.is_empty() {
        out.push_str("### Vaults\n\n");
        for vault in &vaults {
            let notes = store.list_notes(Some(&vault.uid)).unwrap_or_default();
            out.push_str(&format!("- **{}** ({} notes)\n", vault.name, notes.len()));
        }
        out.push('\n');
    }

    // Projects
    let projects = store.list_projects().unwrap_or_default();
    let empty_projects: Vec<crate::config::ProjectConfig> = Vec::new();
    let config_projects: &[crate::config::ProjectConfig] = config
        .map(|c| c.projects.as_slice())
        .unwrap_or(&empty_projects);
    let mut all_project_names: Vec<String> = projects.iter().map(|p| p.name.clone()).collect();
    for cp in config_projects {
        if !all_project_names
            .iter()
            .any(|n| n.eq_ignore_ascii_case(&cp.name))
        {
            all_project_names.push(cp.name.clone());
        }
    }
    if !all_project_names.is_empty() {
        out.push_str("### Projects\n\n");
        for name in &all_project_names {
            out.push_str(&format!("- {name}\n"));
        }
        out.push('\n');
    }

    // Condensed repo map
    if let Ok(map) = crate::query::generate_repo_map(store, 1000) {
        out.push_str("### Architecture map\n\n");
        out.push_str("```\n");
        out.push_str(&map);
        out.push_str("\n```\n");
    }

    Ok(out)
}

/// Generate a Cursor rule file with MDC frontmatter.
///
/// Returns content suitable for writing to `.cursor/rules/nestweaver.mdc`.
pub fn generate_cursor_rule(
    store: &GraphStore,
    config: Option<&InstanceConfig>,
) -> Result<String, anyhow::Error> {
    let _ = (store, config); // no dynamic content needed for the base rule

    let mut out = String::new();

    out.push_str("---\n");
    out.push_str("description: Use NestWeaver for structural codebase understanding and blast radius analysis\n");
    out.push_str("globs:\n");
    out.push_str("alwaysApply: true\n");
    out.push_str("---\n\n");

    out.push_str("When exploring unfamiliar code, use the `brain_context` MCP tool with relevant symbol names as seeds to get PPR-ranked structural context.\n\n");
    out.push_str("Before modifying functions with many callers, use `brain_impact` to check blast radius.\n\n");
    out.push_str("For architecture questions, use `brain_guide` to get the auto-generated codebase intelligence guide.\n\n");
    out.push_str("When working on a named project, use `project_context` to get project-scoped notes and symbols.\n\n");
    out.push_str("After making changes, use `detect_changes` to assess risk.\n");

    Ok(out)
}

/// Generate an AGENTS.md file for Codex with a Codex-specific header.
///
/// Returns the same content as `generate_guide` but prefixed with a
/// Codex-oriented header explaining the file's purpose.
pub fn generate_agents_md(
    store: &GraphStore,
    config: Option<&InstanceConfig>,
) -> Result<String, anyhow::Error> {
    let mut out = String::new();

    out.push_str("# AGENTS.md — Codebase Intelligence Guide\n\n");
    out.push_str("> Auto-generated by NestWeaver. This file helps AI agents understand the codebase structure.\n");
    out.push_str("> NestWeaver provides 17 MCP tools for code intelligence. Run `nestweaver mcp` to start the server.\n\n");

    let guide = generate_guide(store, config)?;
    out.push_str(&guide);

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_guide_produces_valid_markdown() {
        let store = nestweaver_store::GraphStore::in_memory().unwrap();
        let guide = generate_guide(&store, None).unwrap();
        assert!(guide.contains("# Codebase Intelligence Guide"));
        assert!(guide.contains("## NestWeaver Tools"));
        assert!(guide.contains("brain_context"));
    }

    #[test]
    fn generate_skill_produces_yaml_frontmatter() {
        let store = nestweaver_store::GraphStore::in_memory().unwrap();
        let skill = generate_skill(&store, None).unwrap();
        assert!(skill.starts_with("---\n"));
        assert!(skill.contains("name: nestweaver"));
        assert!(skill.contains("description: |"));
        assert!(skill.contains("Do NOT use for simple text search"));
        assert!(skill.contains("brain_context"));
    }

    #[test]
    fn generate_skill_contains_required_sections() {
        let store = nestweaver_store::GraphStore::in_memory().unwrap();
        let skill = generate_skill(&store, None).unwrap();
        // Trigger logic
        assert!(skill.contains("## When to activate"));
        assert!(skill.contains("Do NOT activate when"));
        // Vocabulary
        assert!(skill.contains("## Key concepts"));
        assert!(skill.contains("Seeds"));
        assert!(skill.contains("PPR (Personalized PageRank)"));
        assert!(skill.contains("Confidence"));
        // Tools table
        assert!(skill.contains("## Available MCP tools"));
        assert!(skill.contains("brain_impact"));
        assert!(skill.contains("flow_trace"));
        assert!(skill.contains("detect_changes"));
        assert!(skill.contains("stale_check"));
        assert!(skill.contains("set_extension"));
        assert!(skill.contains("query_extensions"));
        // Workflows
        assert!(skill.contains("## Common workflows"));
        assert!(skill.contains("### Understanding a function"));
        assert!(skill.contains("### Before modifying code"));
        // Query patterns
        assert!(skill.contains("## Graph query patterns"));
        assert!(skill.contains("### Seeding context effectively"));
        // Interpreting results
        assert!(skill.contains("## Interpreting results"));
        assert!(skill.contains("### Confidence scores"));
        assert!(skill.contains("### Impact depth groups"));
    }

    #[test]
    fn generate_cursor_rule_produces_mdc_frontmatter() {
        let store = nestweaver_store::GraphStore::in_memory().unwrap();
        let rule = generate_cursor_rule(&store, None).unwrap();
        assert!(rule.starts_with("---\n"));
        assert!(rule.contains("alwaysApply: true"));
        assert!(rule.contains("brain_context"));
    }

    #[test]
    fn generate_agents_md_produces_codex_header() {
        let store = nestweaver_store::GraphStore::in_memory().unwrap();
        let agents_md = generate_agents_md(&store, None).unwrap();
        assert!(agents_md.starts_with("# AGENTS.md"));
        assert!(agents_md.contains("17 MCP tools"));
        assert!(agents_md.contains("# Codebase Intelligence Guide"));
    }
}
