use nestweaver_store::GraphStore;

use crate::config::InstanceConfig;

/// Generate AGENTS.md content from the indexed graph.
///
/// Returns a markdown string that summarizes the indexed repositories,
/// architectural skeleton, knowledge vaults, and available MCP tools.
/// Intended to be written to `AGENTS.md` at the workspace root so AI
/// agents pick it up automatically at session start.
///
/// Pass an optional `InstanceConfig` to include declared `[[features]]` and
/// `[[links]]` sections in the output. When `None`, those sections are omitted
/// but the cross-repo edges discovered in the graph are still shown.
pub fn generate_guide(
    store: &GraphStore,
    config: Option<&InstanceConfig>,
) -> Result<String, anyhow::Error> {
    let mut out = String::new();

    out.push_str("# Codebase Intelligence Guide\n\n");
    out.push_str("> Auto-generated by NestWeaver. Do not edit manually.\n\n");

    // Section 1: Repositories
    out.push_str("## Repositories\n\n");
    let repos = store.list_repos(None).unwrap_or_default();
    if repos.is_empty() {
        out.push_str("No repositories indexed yet.\n\n");
    } else {
        for repo in &repos {
            let sha_short = if repo.indexed_sha.len() >= 8 {
                &repo.indexed_sha[..8]
            } else {
                &repo.indexed_sha
            };
            out.push_str(&format!("- `{}` (sha: {})\n", repo.url, sha_short));
        }
        out.push('\n');
    }

    // Section 2: Architecture overview (repo map)
    out.push_str("## Architecture\n\n");
    match crate::query::generate_repo_map(store, 2000) {
        Ok(map) => {
            out.push_str("```\n");
            out.push_str(&map);
            out.push_str("\n```\n\n");
        }
        Err(_) => {
            out.push_str("No symbols indexed yet.\n\n");
        }
    }

    // Section 3: Cross-repo links discovered in the graph
    let cross_links = store.list_all_cross_repo_links(50).unwrap_or_default();
    if !cross_links.is_empty() {
        // Build a repo-uid → short name map from indexed repos.
        let repo_name: std::collections::HashMap<String, String> = repos
            .iter()
            .map(|r| {
                // Derive a short name: last path component of the URL.
                let short = r
                    .url
                    .trim_end_matches('/')
                    .rsplit('/')
                    .next()
                    .unwrap_or(&r.url)
                    .trim_end_matches(".git")
                    .to_string();
                (r.uid.clone(), short)
            })
            .collect();

        // Group by (source_repo_uid, target_repo_uid, link_type) to collect shared symbols.
        use std::collections::BTreeMap;
        let mut groups: BTreeMap<(String, String, String), Vec<String>> = BTreeMap::new();
        for link in &cross_links {
            let src_repo = link
                .source_repo_uid
                .as_deref()
                .map(|u| repo_name.get(u).cloned().unwrap_or_else(|| u.to_string()))
                .unwrap_or_else(|| "?".to_string());
            let tgt_repo = link
                .target_repo_uid
                .as_deref()
                .map(|u| repo_name.get(u).cloned().unwrap_or_else(|| u.to_string()))
                .unwrap_or_else(|| "?".to_string());
            groups
                .entry((src_repo, tgt_repo, link.link_type.clone()))
                .or_default()
                .push(link.source_name.clone());
        }

        out.push_str("## Cross-Repository Links\n\n");
        out.push_str("| From | To | Type | Shared Symbols |\n");
        out.push_str("|------|----|------|---------------|\n");
        for ((src, tgt, ltype), mut symbols) in groups {
            symbols.sort();
            symbols.dedup();
            let syms_preview: Vec<&str> = symbols.iter().take(5).map(|s| s.as_str()).collect();
            let syms_str = if symbols.len() > 5 {
                format!("{}, … (+{})", syms_preview.join(", "), symbols.len() - 5)
            } else {
                syms_preview.join(", ")
            };
            out.push_str(&format!("| {src} | {tgt} | {ltype} | {syms_str} |\n"));
        }
        out.push('\n');
    }

    // Section 4: Declared links from instance config
    if let Some(cfg) = config {
        if let Some(links) = &cfg.links
            && !links.is_empty()
        {
            out.push_str("## Declared Links\n\n");
            out.push_str("| From | To | Type | Description |\n");
            out.push_str("|------|----|------|-------------|\n");
            for link in links {
                let desc = link.description.as_deref().unwrap_or("");
                out.push_str(&format!(
                    "| {} | {} | {} | {} |\n",
                    link.from, link.to, link.link_type, desc
                ));
            }
            out.push('\n');
        }

        // Section 5: Feature bundles from instance config
        if let Some(features) = &cfg.features
            && !features.is_empty()
        {
            out.push_str("## Feature Bundles\n\n");
            for feat in features {
                out.push_str(&format!("### {}\n\n", feat.name));
                if let Some(desc) = &feat.description {
                    out.push_str(&format!("> {desc}\n\n"));
                }
                out.push_str(&format!("- **Repos:** {}\n", feat.repos.join(", ")));
                out.push_str(&format!(
                    "- **Entry Points:** {}\n",
                    feat.entry_points.join(", ")
                ));
                out.push('\n');
            }
        }
    }

    // Section 6: Knowledge vaults
    let vaults = store.list_vaults(None).unwrap_or_default();
    if !vaults.is_empty() {
        out.push_str("## Knowledge Vaults\n\n");
        for vault in &vaults {
            let notes = store.list_notes(Some(&vault.uid)).unwrap_or_default();
            out.push_str(&format!("### {} ({} notes)\n\n", vault.name, notes.len()));
            for note in notes.iter().take(20) {
                out.push_str(&format!("- {}\n", note.title));
            }
            if notes.len() > 20 {
                out.push_str(&format!("- ... and {} more\n", notes.len() - 20));
            }
            out.push('\n');
        }
    }

    // Section 8: Available tools
    out.push_str("## NestWeaver Tools\n\n");
    out.push_str("This codebase is indexed by NestWeaver. Available MCP tools:\n\n");
    out.push_str("| Tool | Use when |\n");
    out.push_str("|------|----------|\n");
    out.push_str("| `brain_context` | Exploring unfamiliar code — seeds from symbols, files, or note titles |\n");
    out.push_str("| `brain_search` | Finding symbols or notes by keyword |\n");
    out.push_str("| `note_get` | Reading a vault note's full content |\n");
    out.push_str("| `backlinks` | Finding what links TO a note |\n");
    out.push_str("| `brain_impact` | Checking blast radius before modifying a function |\n");
    out.push_str("| `cross_repo_contracts` | Finding cross-service symbol relationships |\n");
    out.push_str("| `brain_status` | Checking what's indexed |\n");
    out.push('\n');

    // Section 9: CLI + Web
    out.push_str("## Quick Start\n\n");
    out.push_str("```bash\n");
    out.push_str("# Re-index (incremental — only changed files)\n");
    out.push_str("nestweaver index --repo .\n\n");
    out.push_str("# Search for a symbol\n");
    out.push_str("nestweaver search <name>\n\n");
    out.push_str("# Get context for a function\n");
    out.push_str("nestweaver context <name>\n\n");
    out.push_str("# Launch the web UI\n");
    out.push_str("nestweaver ui\n");
    out.push_str("```\n");

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_guide_produces_valid_markdown() {
        let store = nestweaver_store::GraphStore::in_memory().unwrap();
        let guide = generate_guide(&store, None).unwrap();
        assert!(guide.contains("# Codebase Intelligence Guide"));
        assert!(guide.contains("## NestWeaver Tools"));
        assert!(guide.contains("brain_context"));
    }
}
