//! Graph export to Cypher (Neo4j), GraphML, and Mermaid formats.

use std::collections::HashMap;
use std::io::Write;

use nestweaver_store::GraphStore;

// ── Cypher export ────────────────────────────────────────────────────────────

/// Escape a string value for Cypher string literals.
/// Wraps in single quotes, escaping internal single quotes and backslashes.
/// Which subgraph an export should contain.
///
/// nw-173: `export` used to emit ONLY the code subgraph, silently. On a graph
/// holding 1,088 notes and 12,439 headings a full graphml came back with not
/// one Note, Vault, Heading, Section or Tag node — and nothing in the command
/// name, `--help`, or the output said so. Someone loading that file into Gephi
/// or networkx would conclude their vault was not in the graph at all.
///
/// The product's core claim is a UNIFIED graph over code and notes, so `All` is
/// the default: a command named `export` should emit the graph it advertises.
/// The narrower scopes stay available, but now as an explicit choice rather
/// than an unannounced one.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ExportScope {
    /// Code and vault — everything in the graph.
    #[default]
    All,
    /// Repos, files, symbols and their edges.
    Code,
    /// Vaults, notes, headings, sections, tags and their edges.
    Vault,
}

impl ExportScope {
    pub fn includes_code(self) -> bool {
        matches!(self, Self::All | Self::Code)
    }
    pub fn includes_vault(self) -> bool {
        matches!(self, Self::All | Self::Vault)
    }
    pub fn as_str(self) -> &'static str {
        match self {
            Self::All => "all",
            Self::Code => "code",
            Self::Vault => "vault",
        }
    }
}

impl std::str::FromStr for ExportScope {
    type Err = anyhow::Error;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.trim().to_ascii_lowercase().as_str() {
            "all" => Ok(Self::All),
            "code" => Ok(Self::Code),
            "vault" => Ok(Self::Vault),
            other => anyhow::bail!("unknown export scope '{other}' (expected: all, code, vault)"),
        }
    }
}

fn cypher_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() {
        match ch {
            '\'' => out.push_str("\\'"),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out.push('\'');
    out
}

/// Map database edge type labels to cleaner Cypher relationship names.
fn cypher_edge_label(db_label: &str) -> &str {
    match db_label {
        "EXTENDS_SYM" => "EXTENDS",
        "IMPLEMENTS_SYM" => "IMPLEMENTS",
        "INCLUDES_SYM" => "INCLUDES",
        other => other,
    }
}

/// Export the graph as Neo4j Cypher CREATE statements.
///
/// Generates CREATE statements for Repo, File, and Symbol nodes, followed
/// by MATCH/CREATE statements for edges. All values are properly escaped
/// (no string interpolation of raw user data into Cypher structure).
pub fn export_cypher(store: &GraphStore, writer: &mut dyn Write) -> anyhow::Result<()> {
    writeln!(writer, "// NestWeaver graph export — Neo4j Cypher")?;
    writeln!(
        writer,
        "// Generated by `nestweaver export --format cypher`"
    )?;
    writeln!(writer)?;

    // ── Repo nodes ───────────────────────────────────────────────────────
    let repos = store.list_repos(None).map_err(|e| anyhow::anyhow!("{e}"))?;
    for repo in &repos {
        writeln!(
            writer,
            "CREATE (:Repo {{uid: {}, url: {}, indexed_sha: {}, instance_id: {}}});",
            cypher_escape(&repo.uid),
            cypher_escape(&repo.url),
            cypher_escape(&repo.indexed_sha),
            cypher_escape(&repo.instance_id),
        )?;
    }
    if !repos.is_empty() {
        writeln!(writer)?;
    }

    // ── File nodes ───────────────────────────────────────────────────────
    for repo in &repos {
        let files = store
            .list_files_by_repo(&repo.uid)
            .map_err(|e| anyhow::anyhow!("{e}"))?;
        for (file_uid, file_path) in &files {
            writeln!(
                writer,
                "CREATE (:File {{uid: {}, path: {}, repo_uid: {}}});",
                cypher_escape(file_uid),
                cypher_escape(file_path),
                cypher_escape(&repo.uid),
            )?;
        }
    }
    writeln!(writer)?;

    // ── Symbol nodes ─────────────────────────────────────────────────────
    let symbols = store
        .list_all_symbols()
        .map_err(|e| anyhow::anyhow!("{e}"))?;
    // The `pagerank_score` column is never populated; the real scores
    // live in the store's PageRank cache (same source `hubs` reads).
    let pagerank = store
        .pagerank_scores()
        .map_err(|e| anyhow::anyhow!("{e}"))?;
    for sym in &symbols {
        let pr = pagerank
            .get(&sym.uid)
            .copied()
            .or(sym.pagerank_score)
            .unwrap_or(0.0);
        writeln!(
            writer,
            "CREATE (:Symbol {{uid: {}, name: {}, kind: {}, file: {}, line: {}, pagerank: {:.6}}});",
            cypher_escape(&sym.uid),
            cypher_escape(&sym.name),
            cypher_escape(&sym.kind.to_string()),
            cypher_escape(&sym.file_path),
            sym.start_line,
            pr,
        )?;
    }
    if !symbols.is_empty() {
        writeln!(writer)?;
    }

    // ── Edges ────────────────────────────────────────────────────────────
    let typed_edges = store
        .load_typed_edges()
        .map_err(|e| anyhow::anyhow!("{e}"))?;
    for (src, dst, edge_type, confidence, evidence) in &typed_edges {
        if evidence.is_empty() {
            writeln!(
                writer,
                "MATCH (a {{uid: {}}}), (b {{uid: {}}}) CREATE (a)-[:{} {{confidence: {:.4}}}]->(b);",
                cypher_escape(src),
                cypher_escape(dst),
                cypher_edge_label(edge_type),
                confidence,
            )?;
        } else {
            writeln!(
                writer,
                "MATCH (a {{uid: {}}}), (b {{uid: {}}}) CREATE (a)-[:{} {{confidence: {:.4}, evidence: {}}}]->(b);",
                cypher_escape(src),
                cypher_escape(dst),
                cypher_edge_label(edge_type),
                confidence,
                cypher_escape(evidence),
            )?;
        }
    }

    Ok(())
}

// ── GraphML export ───────────────────────────────────────────────────────────

/// Escape a string for safe inclusion in XML attribute values or text content.
fn xml_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            _ => out.push(ch),
        }
    }
    out
}

/// Export the graph as GraphML XML, compatible with Gephi and yEd.
///
/// Emits Repo, File, and Symbol nodes with their properties, and all
/// code-level edges (CALLS, IMPORTS, EXTENDS, IMPLEMENTS, MEMBER_OF, INCLUDES).
pub fn export_graphml(store: &GraphStore, writer: &mut dyn Write) -> anyhow::Result<()> {
    export_graphml_scoped(store, writer, ExportScope::default())
}

/// GraphML export for `scope`.
pub fn export_graphml_scoped(
    store: &GraphStore,
    writer: &mut dyn Write,
    scope: ExportScope,
) -> anyhow::Result<()> {
    // XML header
    writeln!(writer, r#"<?xml version="1.0" encoding="UTF-8"?>"#)?;
    writeln!(
        writer,
        r#"<graphml xmlns="http://graphml.graphdrawing.org/graphml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://graphml.graphdrawing.org/graphml http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">"#
    )?;

    // Key definitions for node attributes
    writeln!(
        writer,
        r#"  <key id="label" for="node" attr.name="label" attr.type="string"/>"#
    )?;
    writeln!(
        writer,
        r#"  <key id="kind" for="node" attr.name="kind" attr.type="string"/>"#
    )?;
    writeln!(
        writer,
        r#"  <key id="file_path" for="node" attr.name="file_path" attr.type="string"/>"#
    )?;
    writeln!(
        writer,
        r#"  <key id="pagerank" for="node" attr.name="pagerank" attr.type="double"/>"#
    )?;

    // Key definitions for edge attributes
    writeln!(
        writer,
        r#"  <key id="edge_type" for="edge" attr.name="type" attr.type="string"/>"#
    )?;
    writeln!(
        writer,
        r#"  <key id="confidence" for="edge" attr.name="confidence" attr.type="double"/>"#
    )?;

    writeln!(writer, r#"  <graph id="G" edgedefault="directed">"#)?;

    // Every id written as a <node>. Edges are filtered against this at the
    // end: a GraphML file referencing an undeclared node is not a valid
    // subgraph — Gephi reports missing-node errors and networkx silently
    // invents thousands of unlabeled phantom nodes. Tracking emission is the
    // only way a scope filter can be honest, because an edge does not know
    // which half of the graph its endpoints came from.
    let mut emitted: std::collections::HashSet<String> = std::collections::HashSet::new();

    // ── Repo nodes ───────────────────────────────────────────────────────
    // Gated on scope: `--scope vault` emitted every Repo and File regardless,
    // so the "vault" export was not the vault subgraph.
    let repos = if scope.includes_code() {
        store.list_repos(None).map_err(|e| anyhow::anyhow!("{e}"))?
    } else {
        Vec::new()
    };
    for repo in &repos {
        emitted.insert(repo.uid.clone());
        writeln!(
            writer,
            r#"    <node id="{}">
      <data key="label">{}</data>
      <data key="kind">Repo</data>
    </node>"#,
            xml_escape(&repo.uid),
            xml_escape(&repo.url),
        )?;
    }

    // ── File nodes ───────────────────────────────────────────────────────
    for repo in &repos {
        let files = store
            .list_files_by_repo(&repo.uid)
            .map_err(|e| anyhow::anyhow!("{e}"))?;
        for (file_uid, file_path) in &files {
            emitted.insert(file_uid.clone());
            writeln!(
                writer,
                r#"    <node id="{}">
      <data key="label">{}</data>
      <data key="kind">File</data>
      <data key="file_path">{}</data>
    </node>"#,
                xml_escape(file_uid),
                xml_escape(file_path),
                xml_escape(file_path),
            )?;
        }
    }

    // ── Symbol nodes ─────────────────────────────────────────────────────
    let symbols = if scope.includes_code() {
        store
            .list_all_symbols()
            .map_err(|e| anyhow::anyhow!("{e}"))?
    } else {
        Vec::new()
    };
    // The `pagerank_score` column is never populated; the real scores
    // live in the store's PageRank cache (same source `hubs` reads).
    let pagerank = store
        .pagerank_scores()
        .map_err(|e| anyhow::anyhow!("{e}"))?;
    for sym in &symbols {
        let pr = pagerank
            .get(&sym.uid)
            .copied()
            .or(sym.pagerank_score)
            .unwrap_or(0.0);
        writeln!(
            writer,
            r#"    <node id="{}">
      <data key="label">{}</data>
      <data key="kind">{}</data>
      <data key="file_path">{}</data>
      <data key="pagerank">{:.6}</data>
    </node>"#,
            xml_escape(&sym.uid),
            xml_escape(&sym.name),
            xml_escape(&sym.kind.to_string()),
            xml_escape(&sym.file_path),
            pr,
        )?;
        emitted.insert(sym.uid.clone());
    }

    // ── Vault nodes ──────────────────────────────────────────────────────
    // nw-173: previously absent ENTIRELY. A full export of a graph holding
    // 1,088 notes and 12,439 headings emitted not one Note, Vault, Heading or
    // Tag, and nothing said so — a consumer loading it into Gephi or networkx
    // would conclude the vault was never indexed. `pagerank` is emitted here
    // for the same reason it is for symbols: a consumer ranking the graph must
    // be able to rank ALL of it.
    if scope.includes_vault() {
        let vaults = store
            .list_vaults(None)
            .map_err(|e| anyhow::anyhow!("{e}"))?;
        for vault in &vaults {
            writeln!(
                writer,
                r#"    <node id="{}">
      <data key="label">{}</data>
      <data key="kind">Vault</data>
      <data key="file_path">{}</data>
      <data key="pagerank">0.000000</data>
    </node>"#,
                xml_escape(&vault.uid),
                xml_escape(&vault.name),
                xml_escape(&vault.root_path),
            )?;
            emitted.insert(vault.uid.clone());
        }

        let notes = store.list_notes(None).map_err(|e| anyhow::anyhow!("{e}"))?;
        for note in &notes {
            let pr = pagerank.get(&note.uid).copied().unwrap_or(0.0);
            writeln!(
                writer,
                r#"    <node id="{}">
      <data key="label">{}</data>
      <data key="kind">Note</data>
      <data key="file_path">{}</data>
      <data key="pagerank">{:.6}</data>
    </node>"#,
                xml_escape(&note.uid),
                xml_escape(&note.title),
                xml_escape(&note.file_path),
                pr,
            )?;
            emitted.insert(note.uid.clone());
        }

        for vault in &vaults {
            let headings = store
                .list_headings_by_vault(&vault.uid)
                .map_err(|e| anyhow::anyhow!("{e}"))?;
            for heading in &headings {
                let pr = pagerank.get(&heading.uid).copied().unwrap_or(0.0);
                writeln!(
                    writer,
                    r#"    <node id="{}">
      <data key="label">{}</data>
      <data key="kind">Heading</data>
      <data key="file_path">{}</data>
      <data key="pagerank">{:.6}</data>
    </node>"#,
                    xml_escape(&heading.uid),
                    xml_escape(&heading.text),
                    xml_escape(&heading.note_uid),
                    pr,
                )?;
                emitted.insert(heading.uid.clone());
            }
        }

        // nw-173: Section nodes are named by this function's own doc comment
        // and by `ExportScope::Vault`, but were never emitted — so HAS_TAG and
        // wikilink edges pointed at `sec:` ids that appeared in no <node>.
        // NOT `list_sections_by_vault`: that traverses NOTE_HAS_SECTION, and
        // the edge is NOT guaranteed — `write.rs` deletes sections by the
        // `note_uid` PROPERTY precisely to catch "fragments whose
        // NOTE_HAS_SECTION edge is missing", and `regex.rs` avoids the
        // traversal for the same reason. Ownership lives on the property, so
        // scan once and keep the sections belonging to notes we emitted.
        {
            let owning_notes: std::collections::HashSet<&str> =
                notes.iter().map(|note| note.uid.as_str()).collect();
            let sections = store
                .list_all_sections()
                .map_err(|e| anyhow::anyhow!("{e}"))?;
            for section in sections
                .iter()
                .filter(|section| owning_notes.contains(section.note_uid.as_str()))
            {
                let pr = pagerank.get(&section.uid).copied().unwrap_or(0.0);
                writeln!(
                    writer,
                    r#"    <node id="{}">
      <data key="label">{}</data>
      <data key="kind">Section</data>
      <data key="file_path">{}</data>
      <data key="pagerank">{:.6}</data>
    </node>"#,
                    xml_escape(&section.uid),
                    // Sections have no title of their own; the line span is
                    // the only human-readable label available.
                    xml_escape(&format!("L{}-{}", section.start_line, section.end_line)),
                    xml_escape(&section.note_uid),
                    pr,
                )?;
                emitted.insert(section.uid.clone());
            }
        }

        let tags = store.list_tags(None).map_err(|e| anyhow::anyhow!("{e}"))?;
        for tag in &tags {
            writeln!(
                writer,
                r#"    <node id="{}">
      <data key="label">{}</data>
      <data key="kind">Tag</data>
      <data key="file_path"></data>
      <data key="pagerank">0.000000</data>
    </node>"#,
                xml_escape(&tag.uid),
                xml_escape(&tag.name),
            )?;
            emitted.insert(tag.uid.clone());
        }
    }

    // ── Edges ────────────────────────────────────────────────────────────
    let typed_edges = store
        .load_typed_edges()
        .map_err(|e| anyhow::anyhow!("{e}"))?;
    // Only edges whose BOTH endpoints were declared above. Previously every
    // edge was written unconditionally, so `--scope vault` emitted every
    // CALLS/IMPORTS edge between `sym:` ids that the file never declared.
    // Re-indexed so ids stay contiguous rather than gapped.
    for (idx, (src, dst, edge_type, confidence, _evidence)) in typed_edges
        .iter()
        .filter(|(src, dst, _, _, _)| emitted.contains(src) && emitted.contains(dst))
        .enumerate()
    {
        writeln!(
            writer,
            r#"    <edge id="e{}" source="{}" target="{}">
      <data key="edge_type">{}</data>
      <data key="confidence">{:.4}</data>
    </edge>"#,
            idx,
            xml_escape(src),
            xml_escape(dst),
            xml_escape(cypher_edge_label(edge_type)),
            confidence,
        )?;
    }

    writeln!(writer, "  </graph>")?;
    writeln!(writer, "</graphml>")?;

    Ok(())
}

/// Render one of the text export formats, applying the scope policy.
///
/// ONE implementation, called by both the direct CLI path and the daemon's
/// `export_graph` RPC. They previously diverged completely: the CLI parsed
/// `--scope` and the daemon neither received nor read it, calling the
/// unscoped `export_graphml`. Since the daemon route is the DEFAULT
/// (`--no-daemon` is the fallback), `--scope` did nothing at all for most
/// users while the engine-level tests passed.
///
/// Returns a notice when the chosen format cannot represent everything the
/// scope asked for, so the caller can say so instead of silently writing less.
pub fn export_text_format(
    store: &GraphStore,
    writer: &mut impl Write,
    format: &str,
    scope: ExportScope,
    top: usize,
) -> anyhow::Result<Option<String>> {
    // Cypher and Mermaid are code-only representations. A VAULT scope is a
    // request they cannot satisfy at all, so they refuse rather than write an
    // empty file and report success.
    if scope == ExportScope::Vault && matches!(format, "cypher" | "mermaid") {
        anyhow::bail!(
            "{format} export is code-only and cannot represent the vault subgraph; \
             use --format graphml for --scope vault"
        );
    }
    match format {
        "cypher" => export_cypher(store, writer)?,
        "mermaid" => export_mermaid(store, top, writer)?,
        "graphml" => export_graphml_scoped(store, writer, scope)?,
        other => anyhow::bail!(
            "unknown export format '{other}' (expected: cypher, graphml, mermaid, msgpack)"
        ),
    }
    // `all` on a code-only format is not an error — it is the default, and
    // failing it would break every existing `export --format cypher`. But the
    // file IS only the code subgraph, and nw-173 exists because that went
    // unsaid.
    Ok(
        (scope == ExportScope::All && matches!(format, "cypher" | "mermaid")).then(|| {
            format!(
                "{format} is a code-only format: this export contains the code subgraph, \
                 not the vault. Use --format graphml for the whole graph."
            )
        }),
    )
}

// ── Mermaid export ───────────────────────────────────────────────────────────

/// Sanitize a string for use as a Mermaid node ID.
/// Removes special characters that break Mermaid syntax.
fn mermaid_id(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// Sanitize a string for use as a Mermaid node label.
/// Wraps in quotes and escapes breaking characters.
fn mermaid_label(s: &str) -> String {
    let escaped: String = s
        .chars()
        .map(|c| match c {
            '"' => '\'',
            '|' | '[' | ']' | '{' | '}' | '(' | ')' | '<' | '>' => '_',
            _ => c,
        })
        .collect();
    format!("\"{escaped}\"")
}

/// Export the top-N symbols (by PageRank) as a Mermaid flowchart, grouped by file.
///
/// Only symbols that appear in the top-N set and edges between them are included.
pub fn export_mermaid(
    store: &GraphStore,
    top_n: usize,
    writer: &mut dyn Write,
) -> anyhow::Result<()> {
    let symbols = store
        .list_all_symbols()
        .map_err(|e| anyhow::anyhow!("{e}"))?;

    // Sort by PageRank descending, take top N. The `pagerank_score`
    // column is never populated; rank by the store's PageRank cache (the same
    // source `hubs` reads), falling back to the column for stores without a
    // computed cache.
    let pagerank = store
        .pagerank_scores()
        .map_err(|e| anyhow::anyhow!("{e}"))?;
    let mut ranked = symbols;
    ranked.sort_by(|a, b| {
        let pa = pagerank
            .get(&a.uid)
            .copied()
            .or(a.pagerank_score)
            .unwrap_or(0.0);
        let pb = pagerank
            .get(&b.uid)
            .copied()
            .or(b.pagerank_score)
            .unwrap_or(0.0);
        pb.partial_cmp(&pa).unwrap_or(std::cmp::Ordering::Equal)
    });
    ranked.truncate(top_n);

    // Build a set of included UIDs for edge filtering.
    let included: std::collections::HashSet<&str> = ranked.iter().map(|s| s.uid.as_str()).collect();

    // Group symbols by file_path for subgraph rendering.
    let mut by_file: HashMap<&str, Vec<&nestweaver_schema::Symbol>> = HashMap::new();
    for sym in &ranked {
        by_file.entry(sym.file_path.as_str()).or_default().push(sym);
    }
    // Sort file groups for deterministic output.
    let mut file_keys: Vec<&str> = by_file.keys().copied().collect();
    file_keys.sort();

    writeln!(writer, "flowchart LR")?;

    // Emit subgraphs grouped by file.
    for file_path in &file_keys {
        let syms = &by_file[file_path];
        let subgraph_id = mermaid_id(file_path);
        writeln!(
            writer,
            "  subgraph {} [{}]",
            subgraph_id,
            mermaid_label(file_path)
        )?;
        for sym in syms {
            let node_id = mermaid_id(&sym.uid);
            let label = format!("{} ({})", sym.name, sym.kind);
            writeln!(writer, "    {}[{}]", node_id, mermaid_label(&label))?;
        }
        writeln!(writer, "  end")?;
    }

    // Emit edges between included symbols.
    let typed_edges = store
        .load_typed_edges()
        .map_err(|e| anyhow::anyhow!("{e}"))?;
    for (src, dst, _edge_type, _confidence, _evidence) in &typed_edges {
        if included.contains(src.as_str()) && included.contains(dst.as_str()) {
            writeln!(writer, "  {} --> {}", mermaid_id(src), mermaid_id(dst))?;
        }
    }

    Ok(())
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use nestweaver_schema::{EdgeType, ResolvedEdge, SymbolKind, Visibility};

    fn test_store() -> GraphStore {
        GraphStore::in_memory().unwrap()
    }

    fn make_symbol(uid: &str, name: &str, file_path: &str) -> nestweaver_schema::Symbol {
        nestweaver_schema::Symbol {
            uid: uid.to_string(),
            name: name.to_string(),
            kind: SymbolKind::Function,
            repo_uid: "repo-1".to_string(),
            file_path: file_path.to_string(),
            start_line: 10,
            end_line: 10,
            signature: format!("fn {name}()"),
            summary: None,
            content_hash: "hash".to_string(),
            embedding: None,
            pagerank_score: Some(0.5),
            is_entry_point: false,
            entry_point_kind: None,
            visibility: Visibility::Inferred,
            type_info: None,
            framework_hint: None,
            canonical_id: None,
        }
    }

    fn populated_store() -> GraphStore {
        let store = test_store();
        store
            .insert_repo(&nestweaver_schema::Repo {
                uid: "repo-1".to_string(),
                url: "https://github.com/example/repo".to_string(),
                indexed_sha: "abc123".to_string(),
                staleness_commits_behind: 0,
                instance_id: "default".to_string(),
                name: None,
                root_path: None,
            })
            .unwrap();

        let sym_a = make_symbol("sym-a", "fn_alpha", "src/alpha.rs");
        let sym_b = make_symbol("sym-b", "fn_beta", "src/beta.rs");
        store.insert_symbol(&sym_a).unwrap();
        store.insert_symbol(&sym_b).unwrap();

        store
            .insert_edge(&ResolvedEdge {
                source_uid: "sym-a".to_string(),
                target_uid: "sym-b".to_string(),
                edge_type: EdgeType::Calls,
                confidence: 0.9,
                link_type: None,
                evidence: vec![],
            })
            .unwrap();

        store
    }

    /// nw-173. A full export must contain the VAULT subgraph, not just code.
    ///
    /// It contained none: a real graph with 1,088 notes and 12,439 headings
    /// exported to graphml with not one Note, Vault, Heading or Tag node, and
    /// nothing in the command name, `--help`, or the output said so. Someone
    /// loading that into Gephi or networkx would conclude their vault had never
    /// been indexed.
    ///
    /// Asserts on the OUTPUT — the nodes a consumer would actually read — not
    /// on whether a vault query was issued.
    #[test]
    fn graphml_export_includes_the_vault_subgraph() {
        use nestweaver_schema::{Note, NoteKind, Vault};

        let store = populated_store();
        store
            .insert_vault(&Vault {
                uid: "vlt:test".to_string(),
                name: "Test Vault".to_string(),
                root_path: "/tmp/vault".to_string(),
                instance_id: "test".to_string(),
            })
            .unwrap();
        store
            .insert_note(&Note {
                uid: "note:test:one".to_string(),
                vault_uid: "vlt:test".to_string(),
                file_path: "one.md".to_string(),
                title: "Note One".to_string(),
                note_kind: NoteKind::General,
                word_count: 3,
                content_hash: "hash".to_string(),
                frontmatter: None,
                created_at: None,
                modified_at: None,
                pagerank_score: None,
                embedding: None,
            })
            .unwrap();
        // A Section, because the export claims to emit them and edges point at
        // them. Without one in the fixture the claim was never tested.
        store
            .insert_section(&nestweaver_schema::Section {
                uid: "sec:test:one:0".to_string(),
                note_uid: "note:test:one".to_string(),
                heading_uid: None,
                start_line: 1,
                end_line: 3,
                text_hash: "hash".to_string(),
                text_content: "body".to_string(),
                word_count: 1,
                pagerank_score: None,
            })
            .unwrap();

        let mut buf = Vec::new();
        export_graphml_scoped(&store, &mut buf, ExportScope::All).unwrap();
        let output = String::from_utf8(buf).unwrap();

        assert!(
            output.contains(r#"<data key="kind">Section</data>"#),
            "a full export must contain Section nodes"
        );
        assert!(
            output.contains(r#"<data key="kind">Vault</data>"#),
            "a full export must contain Vault nodes"
        );
        assert!(
            output.contains(r#"<data key="kind">Note</data>"#),
            "a full export must contain Note nodes"
        );
        assert!(output.contains("Note One"), "and their labels");
        // Code is still there — this widened the export, it did not swap it.
        assert!(output.contains(r#"<data key="kind">Function</data>"#));

        // `--scope code` reproduces the OLD behaviour, now as an explicit
        // choice rather than an unannounced one.
        let mut code_only = Vec::new();
        export_graphml_scoped(&store, &mut code_only, ExportScope::Code).unwrap();
        let code_only = String::from_utf8(code_only).unwrap();
        assert!(!code_only.contains(r#"<data key="kind">Note</data>"#));
        assert!(code_only.contains(r#"<data key="kind">Function</data>"#));

        // …and `--scope vault` is the mirror image.
        let mut vault_only = Vec::new();
        export_graphml_scoped(&store, &mut vault_only, ExportScope::Vault).unwrap();
        let vault_only = String::from_utf8(vault_only).unwrap();
        assert!(vault_only.contains(r#"<data key="kind">Note</data>"#));
        assert!(!vault_only.contains(r#"<data key="kind">Function</data>"#));

        // Absence of Symbol nodes was the ONLY thing asserted here, which is
        // why the scope filter shipped emitting every Repo and File anyway.
        assert!(
            !vault_only.contains(r#"<data key="kind">Repo</data>"#),
            "a vault export must not carry Repo nodes"
        );
        assert!(
            !vault_only.contains(r#"<data key="kind">File</data>"#),
            "a vault export must not carry File nodes"
        );

        // The real invariant: no edge may reference a node the file does not
        // declare. This is what makes a scoped export loadable at all — Gephi
        // errors on a dangling endpoint and networkx invents a phantom node.
        for graph in [&output, &code_only, &vault_only] {
            let declared: std::collections::HashSet<&str> = graph
                .match_indices(r#"<node id=""#)
                .filter_map(|(at, marker)| {
                    let rest = &graph[at + marker.len()..];
                    rest.find('"').map(|end| &rest[..end])
                })
                .collect();
            for (at, marker) in graph.match_indices(r#"<edge id=""#) {
                let rest = &graph[at + marker.len()..];
                for attribute in [r#"source=""#, r#"target=""#] {
                    let from = rest.find(attribute).expect("edge declares both endpoints")
                        + attribute.len();
                    let value = &rest[from..from + rest[from..].find('"').unwrap()];
                    assert!(
                        declared.contains(value),
                        "edge endpoint {value} appears in no <node> element"
                    );
                }
            }
        }
    }

    /// The scope policy both transports share.
    ///
    /// The engine-level scope tests passed while `--scope` did nothing for
    /// users, because the CLI never sent it and the daemon never read it.
    /// Pinning the POLICY in one place is what makes the two routes agree;
    /// pinning `export_graphml_scoped` alone did not.
    #[test]
    fn shared_export_policy_refuses_what_a_format_cannot_represent() {
        let store = populated_store();
        let render = |format: &str, scope: ExportScope| {
            let mut buf = Vec::new();
            export_text_format(&store, &mut buf, format, scope, 10)
                .map(|notice| (String::from_utf8(buf).unwrap(), notice))
        };

        // A vault scope on a code-only format is a request it cannot satisfy.
        for format in ["cypher", "mermaid"] {
            let error = render(format, ExportScope::Vault).unwrap_err();
            assert!(
                format!("{error:#}").contains("code-only"),
                "{format} must refuse --scope vault: {error:#}"
            );
        }

        // `all` is the DEFAULT, so it must not fail — but the file really is
        // code-only, and saying nothing is the nw-173 defect.
        for format in ["cypher", "mermaid"] {
            let (_, notice) = render(format, ExportScope::All).unwrap();
            assert!(
                notice.is_some_and(|n| n.contains("code-only")),
                "{format} at --scope all must say the output is code-only"
            );
        }

        // An explicit code scope asked for exactly what it got: no notice.
        for format in ["cypher", "mermaid"] {
            let (_, notice) = render(format, ExportScope::Code).unwrap();
            assert!(notice.is_none(), "{format} --scope code needs no notice");
        }

        // graphml represents everything, so it never warns and never refuses.
        for scope in [ExportScope::All, ExportScope::Code, ExportScope::Vault] {
            let (output, notice) = render("graphml", scope).unwrap();
            assert!(notice.is_none(), "graphml needs no notice at {scope:?}");
            assert!(
                output.contains("<graphml"),
                "graphml must render at {scope:?}"
            );
        }

        // graphml actually HONOURS the scope through this entry point, not
        // just through `export_graphml_scoped`.
        let (code_only, _) = render("graphml", ExportScope::Code).unwrap();
        assert!(!code_only.contains(r#"<data key="kind">Note</data>"#));

        assert!(render("nonsense", ExportScope::All).is_err());
    }

    #[test]
    fn cypher_export_contains_create_statements() {
        let store = populated_store();
        let mut buf = Vec::new();
        export_cypher(&store, &mut buf).unwrap();
        let output = String::from_utf8(buf).unwrap();

        assert!(output.contains("CREATE (:Repo"));
        assert!(output.contains("CREATE (:Symbol"));
        assert!(output.contains("fn_alpha"));
        assert!(output.contains("fn_beta"));
    }

    #[test]
    fn cypher_export_includes_edges() {
        let store = populated_store();
        let mut buf = Vec::new();
        export_cypher(&store, &mut buf).unwrap();
        let output = String::from_utf8(buf).unwrap();

        assert!(output.contains("MATCH"));
        assert!(output.contains(":CALLS"));
        assert!(output.contains("confidence"));
    }

    #[test]
    fn cypher_escape_handles_special_chars() {
        assert_eq!(cypher_escape("it's"), "'it\\'s'");
        assert_eq!(cypher_escape("a\\b"), "'a\\\\b'");
        assert_eq!(cypher_escape("line\nnew"), "'line\\nnew'");
    }

    #[test]
    fn graphml_export_produces_valid_xml_structure() {
        let store = populated_store();
        let mut buf = Vec::new();
        export_graphml(&store, &mut buf).unwrap();
        let output = String::from_utf8(buf).unwrap();

        assert!(output.contains("<?xml version="));
        assert!(output.contains("<graphml"));
        assert!(output.contains("<graph id="));
        assert!(output.contains("<node id="));
        assert!(output.contains("fn_alpha"));
        assert!(output.contains("fn_beta"));
        assert!(output.contains("</graphml>"));
    }

    #[test]
    fn graphml_export_includes_edges() {
        let store = populated_store();
        let mut buf = Vec::new();
        export_graphml(&store, &mut buf).unwrap();
        let output = String::from_utf8(buf).unwrap();

        assert!(output.contains("<edge id="));
        assert!(output.contains("CALLS"));
        assert!(output.contains("confidence"));
    }

    #[test]
    fn xml_escape_handles_special_chars() {
        assert_eq!(xml_escape("a&b"), "a&amp;b");
        assert_eq!(xml_escape("a<b>c"), "a&lt;b&gt;c");
        assert_eq!(xml_escape(r#"a"b"#), "a&quot;b");
    }

    #[test]
    fn mermaid_export_produces_flowchart() {
        let store = populated_store();
        let mut buf = Vec::new();
        export_mermaid(&store, 50, &mut buf).unwrap();
        let output = String::from_utf8(buf).unwrap();

        assert!(output.starts_with("flowchart LR"));
        assert!(output.contains("subgraph"));
        assert!(output.contains("fn_alpha"));
        assert!(output.contains("fn_beta"));
        // Edge from sym-a to sym-b should be present
        assert!(output.contains("-->"));
    }

    #[test]
    fn mermaid_id_sanitizes_special_chars() {
        assert_eq!(mermaid_id("src/main.rs"), "src_main_rs");
        assert_eq!(mermaid_id("a:b:c"), "a_b_c");
    }

    #[test]
    fn mermaid_top_n_limits_output() {
        let store = test_store();
        // Insert 5 symbols with decreasing PageRank
        for i in 0..5u32 {
            let mut sym = make_symbol(&format!("sym-{i}"), &format!("fn_{i}"), "src/lib.rs");
            sym.pagerank_score = Some(1.0 - (i as f64 * 0.1));
            store.insert_symbol(&sym).unwrap();
        }

        let mut buf = Vec::new();
        export_mermaid(&store, 2, &mut buf).unwrap();
        let output = String::from_utf8(buf).unwrap();

        // Only top 2 should appear
        assert!(output.contains("fn_0"));
        assert!(output.contains("fn_1"));
        assert!(!output.contains("fn_4"));
    }

    /// populated_store plus a second caller of sym-b: two callers make the
    /// callee's computed PageRank strictly higher than each caller's (with a
    /// single caller the store's reverse-edge weighting ties them at 0.5).
    /// Every symbol carries the same 0.5 column score, so any difference in
    /// the exported values must come from the cache — a real regression.
    fn ranked_store() -> GraphStore {
        let store = populated_store();
        store
            .insert_symbol(&make_symbol("sym-c", "fn_gamma", "src/gamma.rs"))
            .unwrap();
        store
            .insert_edge(&ResolvedEdge {
                source_uid: "sym-c".to_string(),
                target_uid: "sym-b".to_string(),
                edge_type: EdgeType::Calls,
                confidence: 0.9,
                link_type: None,
                evidence: vec![],
            })
            .unwrap();
        store
    }

    #[test]
    fn export_uses_computed_pagerank_not_zero_column() {
        // The `pagerank_score` column is never populated in production;
        // export must carry the store's computed PageRank cache values.
        let store = ranked_store();
        let scores = store.pagerank_scores().unwrap();
        assert!(
            scores.contains_key("sym-b"),
            "cache should compute scores on demand"
        );
        assert!(
            (scores["sym-b"] - 0.5).abs() > 1e-9,
            "cache score must differ from the 0.5 column value to prove the source: {scores:?}"
        );

        let mut buf = Vec::new();
        export_cypher(&store, &mut buf).unwrap();
        let output = String::from_utf8(buf).unwrap();
        let expected = format!("pagerank: {:.6}", scores["sym-b"]);
        assert!(
            output.contains(&expected),
            "cypher export must carry the cache score {expected}"
        );

        let mut buf = Vec::new();
        export_graphml(&store, &mut buf).unwrap();
        let output = String::from_utf8(buf).unwrap();
        let expected = format!("<data key=\"pagerank\">{:.6}</data>", scores["sym-b"]);
        assert!(
            output.contains(&expected),
            "graphml export must carry the cache score {expected}"
        );
    }

    #[test]
    fn mermaid_top_n_ranks_by_computed_pagerank() {
        // Note: make_symbol gives every symbol the same column score (0.5),
        // but sym-b has two inbound CALLS edges, so the computed PageRank
        // must rank it first.
        let store = ranked_store();
        let scores = store.pagerank_scores().unwrap();
        assert!(
            scores["sym-b"] > scores["sym-a"],
            "callee must outrank caller: {scores:?}"
        );
        let mut buf = Vec::new();
        export_mermaid(&store, 1, &mut buf).unwrap();
        let output = String::from_utf8(buf).unwrap();
        assert!(output.contains("fn_beta"), "top-1 must be the callee");
        assert!(!output.contains("fn_alpha"), "top-1 must not be the caller");
    }

    #[test]
    fn export_empty_store_produces_valid_output() {
        let store = test_store();

        let mut buf = Vec::new();
        export_cypher(&store, &mut buf).unwrap();
        let cypher = String::from_utf8(buf).unwrap();
        assert!(cypher.contains("NestWeaver graph export"));

        let mut buf = Vec::new();
        export_graphml(&store, &mut buf).unwrap();
        let graphml = String::from_utf8(buf).unwrap();
        assert!(graphml.contains("</graphml>"));

        let mut buf = Vec::new();
        export_mermaid(&store, 50, &mut buf).unwrap();
        let mermaid = String::from_utf8(buf).unwrap();
        assert!(mermaid.starts_with("flowchart LR"));
    }
}
