//! Graph export to Cypher (Neo4j), GraphML, and Mermaid formats.

use std::collections::HashMap;
use std::io::Write;

use nestweaver_store::GraphStore;

// ── Cypher export ────────────────────────────────────────────────────────────

/// Escape a string value for Cypher string literals.
/// Wraps in single quotes, escaping internal single quotes and backslashes.
fn cypher_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() {
        match ch {
            '\'' => out.push_str("\\'"),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out.push('\'');
    out
}

/// Map database edge type labels to cleaner Cypher relationship names.
fn cypher_edge_label(db_label: &str) -> &str {
    match db_label {
        "EXTENDS_SYM" => "EXTENDS",
        "IMPLEMENTS_SYM" => "IMPLEMENTS",
        "INCLUDES_SYM" => "INCLUDES",
        other => other,
    }
}

/// Export the graph as Neo4j Cypher CREATE statements.
///
/// Generates CREATE statements for Repo, File, and Symbol nodes, followed
/// by MATCH/CREATE statements for edges. All values are properly escaped
/// (no string interpolation of raw user data into Cypher structure).
pub fn export_cypher(store: &GraphStore, writer: &mut dyn Write) -> anyhow::Result<()> {
    writeln!(writer, "// NestWeaver graph export — Neo4j Cypher")?;
    writeln!(
        writer,
        "// Generated by `nestweaver export --format cypher`"
    )?;
    writeln!(writer)?;

    // ── Repo nodes ───────────────────────────────────────────────────────
    let repos = store.list_repos(None).map_err(|e| anyhow::anyhow!("{e}"))?;
    for repo in &repos {
        writeln!(
            writer,
            "CREATE (:Repo {{uid: {}, url: {}, indexed_sha: {}, instance_id: {}}});",
            cypher_escape(&repo.uid),
            cypher_escape(&repo.url),
            cypher_escape(&repo.indexed_sha),
            cypher_escape(&repo.instance_id),
        )?;
    }
    if !repos.is_empty() {
        writeln!(writer)?;
    }

    // ── File nodes ───────────────────────────────────────────────────────
    for repo in &repos {
        let files = store
            .list_files_by_repo(&repo.uid)
            .map_err(|e| anyhow::anyhow!("{e}"))?;
        for (file_uid, file_path) in &files {
            writeln!(
                writer,
                "CREATE (:File {{uid: {}, path: {}, repo_uid: {}}});",
                cypher_escape(file_uid),
                cypher_escape(file_path),
                cypher_escape(&repo.uid),
            )?;
        }
    }
    writeln!(writer)?;

    // ── Symbol nodes ─────────────────────────────────────────────────────
    let symbols = store
        .list_all_symbols()
        .map_err(|e| anyhow::anyhow!("{e}"))?;
    // F-13: the `pagerank_score` column is never populated; the real scores
    // live in the store's PageRank cache (same source `hubs` reads).
    let pagerank = store.pagerank_scores();
    for sym in &symbols {
        let pr = pagerank
            .get(&sym.uid)
            .copied()
            .or(sym.pagerank_score)
            .unwrap_or(0.0);
        writeln!(
            writer,
            "CREATE (:Symbol {{uid: {}, name: {}, kind: {}, file: {}, line: {}, pagerank: {:.6}}});",
            cypher_escape(&sym.uid),
            cypher_escape(&sym.name),
            cypher_escape(&sym.kind.to_string()),
            cypher_escape(&sym.file_path),
            sym.start_line,
            pr,
        )?;
    }
    if !symbols.is_empty() {
        writeln!(writer)?;
    }

    // ── Edges ────────────────────────────────────────────────────────────
    let typed_edges = store
        .load_typed_edges()
        .map_err(|e| anyhow::anyhow!("{e}"))?;
    for (src, dst, edge_type, confidence, evidence) in &typed_edges {
        if evidence.is_empty() {
            writeln!(
                writer,
                "MATCH (a {{uid: {}}}), (b {{uid: {}}}) CREATE (a)-[:{} {{confidence: {:.4}}}]->(b);",
                cypher_escape(src),
                cypher_escape(dst),
                cypher_edge_label(edge_type),
                confidence,
            )?;
        } else {
            writeln!(
                writer,
                "MATCH (a {{uid: {}}}), (b {{uid: {}}}) CREATE (a)-[:{} {{confidence: {:.4}, evidence: {}}}]->(b);",
                cypher_escape(src),
                cypher_escape(dst),
                cypher_edge_label(edge_type),
                confidence,
                cypher_escape(evidence),
            )?;
        }
    }

    Ok(())
}

// ── GraphML export ───────────────────────────────────────────────────────────

/// Escape a string for safe inclusion in XML attribute values or text content.
fn xml_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            _ => out.push(ch),
        }
    }
    out
}

/// Export the graph as GraphML XML, compatible with Gephi and yEd.
///
/// Emits Repo, File, and Symbol nodes with their properties, and all
/// code-level edges (CALLS, IMPORTS, EXTENDS, IMPLEMENTS, MEMBER_OF, INCLUDES).
pub fn export_graphml(store: &GraphStore, writer: &mut dyn Write) -> anyhow::Result<()> {
    // XML header
    writeln!(writer, r#"<?xml version="1.0" encoding="UTF-8"?>"#)?;
    writeln!(
        writer,
        r#"<graphml xmlns="http://graphml.graphdrawing.org/graphml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://graphml.graphdrawing.org/graphml http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">"#
    )?;

    // Key definitions for node attributes
    writeln!(
        writer,
        r#"  <key id="label" for="node" attr.name="label" attr.type="string"/>"#
    )?;
    writeln!(
        writer,
        r#"  <key id="kind" for="node" attr.name="kind" attr.type="string"/>"#
    )?;
    writeln!(
        writer,
        r#"  <key id="file_path" for="node" attr.name="file_path" attr.type="string"/>"#
    )?;
    writeln!(
        writer,
        r#"  <key id="pagerank" for="node" attr.name="pagerank" attr.type="double"/>"#
    )?;

    // Key definitions for edge attributes
    writeln!(
        writer,
        r#"  <key id="edge_type" for="edge" attr.name="type" attr.type="string"/>"#
    )?;
    writeln!(
        writer,
        r#"  <key id="confidence" for="edge" attr.name="confidence" attr.type="double"/>"#
    )?;

    writeln!(writer, r#"  <graph id="G" edgedefault="directed">"#)?;

    // ── Repo nodes ───────────────────────────────────────────────────────
    let repos = store.list_repos(None).map_err(|e| anyhow::anyhow!("{e}"))?;
    for repo in &repos {
        writeln!(
            writer,
            r#"    <node id="{}">
      <data key="label">{}</data>
      <data key="kind">Repo</data>
    </node>"#,
            xml_escape(&repo.uid),
            xml_escape(&repo.url),
        )?;
    }

    // ── File nodes ───────────────────────────────────────────────────────
    for repo in &repos {
        let files = store
            .list_files_by_repo(&repo.uid)
            .map_err(|e| anyhow::anyhow!("{e}"))?;
        for (file_uid, file_path) in &files {
            writeln!(
                writer,
                r#"    <node id="{}">
      <data key="label">{}</data>
      <data key="kind">File</data>
      <data key="file_path">{}</data>
    </node>"#,
                xml_escape(file_uid),
                xml_escape(file_path),
                xml_escape(file_path),
            )?;
        }
    }

    // ── Symbol nodes ─────────────────────────────────────────────────────
    let symbols = store
        .list_all_symbols()
        .map_err(|e| anyhow::anyhow!("{e}"))?;
    // F-13: the `pagerank_score` column is never populated; the real scores
    // live in the store's PageRank cache (same source `hubs` reads).
    let pagerank = store.pagerank_scores();
    for sym in &symbols {
        let pr = pagerank
            .get(&sym.uid)
            .copied()
            .or(sym.pagerank_score)
            .unwrap_or(0.0);
        writeln!(
            writer,
            r#"    <node id="{}">
      <data key="label">{}</data>
      <data key="kind">{}</data>
      <data key="file_path">{}</data>
      <data key="pagerank">{:.6}</data>
    </node>"#,
            xml_escape(&sym.uid),
            xml_escape(&sym.name),
            xml_escape(&sym.kind.to_string()),
            xml_escape(&sym.file_path),
            pr,
        )?;
    }

    // ── Edges ────────────────────────────────────────────────────────────
    let typed_edges = store
        .load_typed_edges()
        .map_err(|e| anyhow::anyhow!("{e}"))?;
    for (idx, (src, dst, edge_type, confidence, _evidence)) in typed_edges.iter().enumerate() {
        writeln!(
            writer,
            r#"    <edge id="e{}" source="{}" target="{}">
      <data key="edge_type">{}</data>
      <data key="confidence">{:.4}</data>
    </edge>"#,
            idx,
            xml_escape(src),
            xml_escape(dst),
            xml_escape(cypher_edge_label(edge_type)),
            confidence,
        )?;
    }

    writeln!(writer, "  </graph>")?;
    writeln!(writer, "</graphml>")?;

    Ok(())
}

// ── Mermaid export ───────────────────────────────────────────────────────────

/// Sanitize a string for use as a Mermaid node ID.
/// Removes special characters that break Mermaid syntax.
fn mermaid_id(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// Sanitize a string for use as a Mermaid node label.
/// Wraps in quotes and escapes breaking characters.
fn mermaid_label(s: &str) -> String {
    let escaped: String = s
        .chars()
        .map(|c| match c {
            '"' => '\'',
            '|' | '[' | ']' | '{' | '}' | '(' | ')' | '<' | '>' => '_',
            _ => c,
        })
        .collect();
    format!("\"{escaped}\"")
}

/// Export the top-N symbols (by PageRank) as a Mermaid flowchart, grouped by file.
///
/// Only symbols that appear in the top-N set and edges between them are included.
pub fn export_mermaid(
    store: &GraphStore,
    top_n: usize,
    writer: &mut dyn Write,
) -> anyhow::Result<()> {
    let symbols = store
        .list_all_symbols()
        .map_err(|e| anyhow::anyhow!("{e}"))?;

    // Sort by PageRank descending, take top N. F-13: the `pagerank_score`
    // column is never populated; rank by the store's PageRank cache (the same
    // source `hubs` reads), falling back to the column for stores without a
    // computed cache.
    let pagerank = store.pagerank_scores();
    let mut ranked = symbols;
    ranked.sort_by(|a, b| {
        let pa = pagerank
            .get(&a.uid)
            .copied()
            .or(a.pagerank_score)
            .unwrap_or(0.0);
        let pb = pagerank
            .get(&b.uid)
            .copied()
            .or(b.pagerank_score)
            .unwrap_or(0.0);
        pb.partial_cmp(&pa).unwrap_or(std::cmp::Ordering::Equal)
    });
    ranked.truncate(top_n);

    // Build a set of included UIDs for edge filtering.
    let included: std::collections::HashSet<&str> = ranked.iter().map(|s| s.uid.as_str()).collect();

    // Group symbols by file_path for subgraph rendering.
    let mut by_file: HashMap<&str, Vec<&nestweaver_schema::Symbol>> = HashMap::new();
    for sym in &ranked {
        by_file.entry(sym.file_path.as_str()).or_default().push(sym);
    }
    // Sort file groups for deterministic output.
    let mut file_keys: Vec<&str> = by_file.keys().copied().collect();
    file_keys.sort();

    writeln!(writer, "flowchart LR")?;

    // Emit subgraphs grouped by file.
    for file_path in &file_keys {
        let syms = &by_file[file_path];
        let subgraph_id = mermaid_id(file_path);
        writeln!(
            writer,
            "  subgraph {} [{}]",
            subgraph_id,
            mermaid_label(file_path)
        )?;
        for sym in syms {
            let node_id = mermaid_id(&sym.uid);
            let label = format!("{} ({})", sym.name, sym.kind);
            writeln!(writer, "    {}[{}]", node_id, mermaid_label(&label))?;
        }
        writeln!(writer, "  end")?;
    }

    // Emit edges between included symbols.
    let typed_edges = store
        .load_typed_edges()
        .map_err(|e| anyhow::anyhow!("{e}"))?;
    for (src, dst, _edge_type, _confidence, _evidence) in &typed_edges {
        if included.contains(src.as_str()) && included.contains(dst.as_str()) {
            writeln!(writer, "  {} --> {}", mermaid_id(src), mermaid_id(dst))?;
        }
    }

    Ok(())
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use nestweaver_schema::{EdgeType, ResolvedEdge, SymbolKind, Visibility};

    fn test_store() -> GraphStore {
        GraphStore::in_memory().unwrap()
    }

    fn make_symbol(uid: &str, name: &str, file_path: &str) -> nestweaver_schema::Symbol {
        nestweaver_schema::Symbol {
            uid: uid.to_string(),
            name: name.to_string(),
            kind: SymbolKind::Function,
            repo_uid: "repo-1".to_string(),
            file_path: file_path.to_string(),
            start_line: 10,
            end_line: 10,
            signature: format!("fn {name}()"),
            summary: None,
            content_hash: "hash".to_string(),
            embedding: None,
            pagerank_score: Some(0.5),
            is_entry_point: false,
            entry_point_kind: None,
            visibility: Visibility::Inferred,
            type_info: None,
            framework_hint: None,
            canonical_id: None,
        }
    }

    fn populated_store() -> GraphStore {
        let store = test_store();
        store
            .insert_repo(&nestweaver_schema::Repo {
                uid: "repo-1".to_string(),
                url: "https://github.com/example/repo".to_string(),
                indexed_sha: "abc123".to_string(),
                staleness_commits_behind: 0,
                instance_id: "default".to_string(),
                name: None,
                root_path: None,
            })
            .unwrap();

        let sym_a = make_symbol("sym-a", "fn_alpha", "src/alpha.rs");
        let sym_b = make_symbol("sym-b", "fn_beta", "src/beta.rs");
        store.insert_symbol(&sym_a).unwrap();
        store.insert_symbol(&sym_b).unwrap();

        store
            .insert_edge(&ResolvedEdge {
                source_uid: "sym-a".to_string(),
                target_uid: "sym-b".to_string(),
                edge_type: EdgeType::Calls,
                confidence: 0.9,
                link_type: None,
                evidence: vec![],
            })
            .unwrap();

        store
    }

    #[test]
    fn cypher_export_contains_create_statements() {
        let store = populated_store();
        let mut buf = Vec::new();
        export_cypher(&store, &mut buf).unwrap();
        let output = String::from_utf8(buf).unwrap();

        assert!(output.contains("CREATE (:Repo"));
        assert!(output.contains("CREATE (:Symbol"));
        assert!(output.contains("fn_alpha"));
        assert!(output.contains("fn_beta"));
    }

    #[test]
    fn cypher_export_includes_edges() {
        let store = populated_store();
        let mut buf = Vec::new();
        export_cypher(&store, &mut buf).unwrap();
        let output = String::from_utf8(buf).unwrap();

        assert!(output.contains("MATCH"));
        assert!(output.contains(":CALLS"));
        assert!(output.contains("confidence"));
    }

    #[test]
    fn cypher_escape_handles_special_chars() {
        assert_eq!(cypher_escape("it's"), "'it\\'s'");
        assert_eq!(cypher_escape("a\\b"), "'a\\\\b'");
        assert_eq!(cypher_escape("line\nnew"), "'line\\nnew'");
    }

    #[test]
    fn graphml_export_produces_valid_xml_structure() {
        let store = populated_store();
        let mut buf = Vec::new();
        export_graphml(&store, &mut buf).unwrap();
        let output = String::from_utf8(buf).unwrap();

        assert!(output.contains("<?xml version="));
        assert!(output.contains("<graphml"));
        assert!(output.contains("<graph id="));
        assert!(output.contains("<node id="));
        assert!(output.contains("fn_alpha"));
        assert!(output.contains("fn_beta"));
        assert!(output.contains("</graphml>"));
    }

    #[test]
    fn graphml_export_includes_edges() {
        let store = populated_store();
        let mut buf = Vec::new();
        export_graphml(&store, &mut buf).unwrap();
        let output = String::from_utf8(buf).unwrap();

        assert!(output.contains("<edge id="));
        assert!(output.contains("CALLS"));
        assert!(output.contains("confidence"));
    }

    #[test]
    fn xml_escape_handles_special_chars() {
        assert_eq!(xml_escape("a&b"), "a&amp;b");
        assert_eq!(xml_escape("a<b>c"), "a&lt;b&gt;c");
        assert_eq!(xml_escape(r#"a"b"#), "a&quot;b");
    }

    #[test]
    fn mermaid_export_produces_flowchart() {
        let store = populated_store();
        let mut buf = Vec::new();
        export_mermaid(&store, 50, &mut buf).unwrap();
        let output = String::from_utf8(buf).unwrap();

        assert!(output.starts_with("flowchart LR"));
        assert!(output.contains("subgraph"));
        assert!(output.contains("fn_alpha"));
        assert!(output.contains("fn_beta"));
        // Edge from sym-a to sym-b should be present
        assert!(output.contains("-->"));
    }

    #[test]
    fn mermaid_id_sanitizes_special_chars() {
        assert_eq!(mermaid_id("src/main.rs"), "src_main_rs");
        assert_eq!(mermaid_id("a:b:c"), "a_b_c");
    }

    #[test]
    fn mermaid_top_n_limits_output() {
        let store = test_store();
        // Insert 5 symbols with decreasing PageRank
        for i in 0..5u32 {
            let mut sym = make_symbol(&format!("sym-{i}"), &format!("fn_{i}"), "src/lib.rs");
            sym.pagerank_score = Some(1.0 - (i as f64 * 0.1));
            store.insert_symbol(&sym).unwrap();
        }

        let mut buf = Vec::new();
        export_mermaid(&store, 2, &mut buf).unwrap();
        let output = String::from_utf8(buf).unwrap();

        // Only top 2 should appear
        assert!(output.contains("fn_0"));
        assert!(output.contains("fn_1"));
        assert!(!output.contains("fn_4"));
    }

    /// populated_store plus a second caller of sym-b: two callers make the
    /// callee's computed PageRank strictly higher than each caller's (with a
    /// single caller the store's reverse-edge weighting ties them at 0.5).
    /// Every symbol carries the same 0.5 column score, so any difference in
    /// the exported values must come from the cache — a real F-13 regression.
    fn ranked_store() -> GraphStore {
        let store = populated_store();
        store
            .insert_symbol(&make_symbol("sym-c", "fn_gamma", "src/gamma.rs"))
            .unwrap();
        store
            .insert_edge(&ResolvedEdge {
                source_uid: "sym-c".to_string(),
                target_uid: "sym-b".to_string(),
                edge_type: EdgeType::Calls,
                confidence: 0.9,
                link_type: None,
                evidence: vec![],
            })
            .unwrap();
        store
    }

    #[test]
    fn export_uses_computed_pagerank_not_zero_column() {
        // F-13: the `pagerank_score` column is never populated in production;
        // export must carry the store's computed PageRank cache values.
        let store = ranked_store();
        let scores = store.pagerank_scores();
        assert!(
            scores.contains_key("sym-b"),
            "cache should compute scores on demand"
        );
        assert!(
            (scores["sym-b"] - 0.5).abs() > 1e-9,
            "cache score must differ from the 0.5 column value to prove the source: {scores:?}"
        );

        let mut buf = Vec::new();
        export_cypher(&store, &mut buf).unwrap();
        let output = String::from_utf8(buf).unwrap();
        let expected = format!("pagerank: {:.6}", scores["sym-b"]);
        assert!(
            output.contains(&expected),
            "cypher export must carry the cache score {expected}"
        );

        let mut buf = Vec::new();
        export_graphml(&store, &mut buf).unwrap();
        let output = String::from_utf8(buf).unwrap();
        let expected = format!("<data key=\"pagerank\">{:.6}</data>", scores["sym-b"]);
        assert!(
            output.contains(&expected),
            "graphml export must carry the cache score {expected}"
        );
    }

    #[test]
    fn mermaid_top_n_ranks_by_computed_pagerank() {
        // F-13: make_symbol gives every symbol the same column score (0.5),
        // but sym-b has two inbound CALLS edges, so the computed PageRank
        // must rank it first.
        let store = ranked_store();
        let scores = store.pagerank_scores();
        assert!(
            scores["sym-b"] > scores["sym-a"],
            "callee must outrank caller: {scores:?}"
        );
        let mut buf = Vec::new();
        export_mermaid(&store, 1, &mut buf).unwrap();
        let output = String::from_utf8(buf).unwrap();
        assert!(output.contains("fn_beta"), "top-1 must be the callee");
        assert!(!output.contains("fn_alpha"), "top-1 must not be the caller");
    }

    #[test]
    fn export_empty_store_produces_valid_output() {
        let store = test_store();

        let mut buf = Vec::new();
        export_cypher(&store, &mut buf).unwrap();
        let cypher = String::from_utf8(buf).unwrap();
        assert!(cypher.contains("NestWeaver graph export"));

        let mut buf = Vec::new();
        export_graphml(&store, &mut buf).unwrap();
        let graphml = String::from_utf8(buf).unwrap();
        assert!(graphml.contains("</graphml>"));

        let mut buf = Vec::new();
        export_mermaid(&store, 50, &mut buf).unwrap();
        let mermaid = String::from_utf8(buf).unwrap();
        assert!(mermaid.starts_with("flowchart LR"));
    }
}
