[package]
name = "nestweaver-web"
version.workspace = true
edition = "2024"

[dependencies]
nestweaver-algorithms = { workspace = true }
nestweaver-engine = { workspace = true }
nestweaver-store = { workspace = true }
nestweaver-schema = { workspace = true }
rmp-serde = "1"
axum = { workspace = true }
rust-embed = { workspace = true }
tower-http = { workspace = true }
tokio = { version = "1", features = ["full"] }
tokio-stream = { workspace = true, features = ["sync"] }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
open = { workspace = true }
futures = "0.3"
url = "2"
prometheus = "0.14"
subtle = { workspace = true }

[dev-dependencies]
tempfile = "3"
tokio = { version = "1", features = ["full", "test-util"] }
tower = { version = "0.5", features = ["util"] }
