//! Emits `RESPONSE_SHAPE_VERSION`: a content digest of the Rust sources that
//! determine MCP tool response *shapes*.
//!
//! # Why this is derived and not hand-maintained
//!
//! The F16 response cache (`nestweaver_store::cache`) validates an entry on
//! `graph_generation` + `scope_digest` + a 24h TTL. All three describe the
//! GRAPH; none of them describes the BINARY. So a release that adds a field to
//! a cached tool's response (e.g. `brain_search` gaining `semantic_applied` /
//! `degraded_components`) keeps hitting entries written by the PREVIOUS binary
//! for up to 24h and serves the OLD shape — silently reintroducing exactly the
//! ambiguity the new field exists to remove.
//!
//! A constant that a human must remember to bump would fix that release and
//! fail the next one. This digest is derived from the sources themselves, so
//! any change to any workspace crate's `src/` changes it and the cache
//! invalidates *by construction*.
//!
//! It is deliberately over-broad: a comment-only edit also invalidates the
//! cache. That is the correct direction to be wrong in — over-invalidation
//! costs one recompute, under-invalidation costs correctness.

use std::hash::{Hash, Hasher};
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is always set by cargo"),
    );
    let out_dir =
        PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR is always set by cargo"));

    // Prefer every workspace crate's `src/` (response shapes are assembled from
    // -mcp, -engine, -federation, -proto and -store together). Fall back to
    // this crate's own `src/` when the sibling layout is absent — e.g. a
    // packaged/vendored build of this crate alone. That fallback is a weaker
    // guarantee (a shape change made only in a sibling crate would not move the
    // digest) and is recorded in the generated file so it is visible.
    let crates_dir = manifest_dir.parent().map(Path::to_path_buf);
    let mut roots: Vec<PathBuf> = Vec::new();
    if let Some(crates_dir) = crates_dir.as_ref()
        && let Ok(entries) = std::fs::read_dir(crates_dir)
    {
        let mut siblings: Vec<PathBuf> = entries
            .flatten()
            .map(|entry| entry.path().join("src"))
            .filter(|src| src.is_dir())
            .collect();
        siblings.sort();
        roots = siblings;
    }
    let workspace_wide = roots.len() > 1;
    if !workspace_wide {
        roots = vec![manifest_dir.join("src")];
    }

    let mut files: Vec<PathBuf> = Vec::new();
    for root in &roots {
        println!("cargo:rerun-if-changed={}", root.display());
        collect_rust_sources(root, &mut files);
    }
    // Sort so the digest does not depend on directory iteration order.
    files.sort();

    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    "nestweaver-response-shape-v1".hash(&mut hasher);
    std::env::var("CARGO_PKG_VERSION")
        .unwrap_or_default()
        .hash(&mut hasher);
    let mut hashed = 0usize;
    for file in &files {
        let Ok(bytes) = std::fs::read(file) else {
            continue;
        };
        // Hash the path relative to its root so an absolute checkout location
        // (which does not change behavior) does not change the digest.
        let relative = roots
            .iter()
            .find_map(|root| file.strip_prefix(root).ok().map(|rest| (root, rest)))
            .map(|(root, rest)| {
                let crate_name = root
                    .parent()
                    .and_then(Path::file_name)
                    .map(|n| n.to_string_lossy().into_owned())
                    .unwrap_or_default();
                format!("{crate_name}/{}", rest.display())
            })
            .unwrap_or_else(|| file.display().to_string());
        relative.replace('\\', "/").hash(&mut hasher);
        bytes.hash(&mut hasher);
        hashed += 1;
    }
    // A digest over zero files would be a constant, i.e. no protection at all.
    // Fail the build rather than ship a cache that cannot tell binaries apart.
    assert!(
        hashed > 0,
        "response-shape digest hashed no sources under {roots:?}; \
         the response cache would not be able to distinguish binaries"
    );
    let digest = hasher.finish();

    let generated = format!(
        "// @generated by build.rs — do not edit.\n\
         /// Digest of the sources that determine MCP tool response shapes.\n\
         /// Sources hashed: {hashed} file(s); workspace-wide: {workspace_wide}.\n\
         pub const RESPONSE_SHAPE_VERSION: u64 = {digest}u64;\n"
    );
    std::fs::write(out_dir.join("response_shape_version.rs"), generated)
        .expect("write response_shape_version.rs");

    println!("cargo:rerun-if-changed=build.rs");
}

fn collect_rust_sources(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_rust_sources(&path, out);
        } else if path.extension().is_some_and(|ext| ext == "rs") {
            out.push(path);
        }
    }
}
