[package]
name = "nestweaver-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
nestweaver-algorithms = { workspace = true }
nestweaver-schema = { workspace = true }
nestweaver-parser = { workspace = true }
nestweaver-resolver = { workspace = true }
nestweaver-store = { workspace = true }
nestweaver-storage = { workspace = true }
rmp-serde = "1"
serde = { workspace = true }
serde_json = { workspace = true }
blake3 = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
toml = "1.1"
serde_yaml = "0.9"
serde_yaml_ng = "0.10"
openapiv3 = "2"
protox-parse = "0.9"
prost-types = "0.14"
apollo-parser = "0.8"
reqwest = { version = "0.13", features = ["json", "query"] }
walkdir = "2"
ignore = "0.4"
indicatif = "0.17"
notify = "8"
notify-debouncer-mini = { version = "0.7", default-features = false }
rand = "0.10"
rusqlite = { workspace = true }
libc = "0.2"
tokio = { version = "1", features = ["rt", "sync", "time", "macros"] }
rayon = "1.10"
globset = "0.4"
url = "2"
html2md = "0.2"
sha2 = { workspace = true }
tar = "0.4"
tempfile = "3"
zstd = "0.13"
rcgen = "0.14"
time = "0.3"
nestweaver-embed = { path = "../nestweaver-embed", optional = true }

[features]
embed = ["dep:nestweaver-embed"]

[dev-dependencies]
tempfile = "3"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
wiremock = "0.6"
