[package]
name = "nestweaver-store"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
nestweaver-algorithms = { workspace = true }
nestweaver-schema = { workspace = true }
lbug = "0.17.1"
lru = "0.16"
tantivy = { version = "0.26", default-features = false, features = ["mmap", "stopwords", "lz4-compression", "stemmer"] }
regex = "1.12"
regex-syntax = "0.8"
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
rayon = { workspace = true }
zstd = "0.13"
rmp-serde = "1"

[build-dependencies]
cc = "1"

[dev-dependencies]
tempfile = "3"
