import type { PhraseCoverageEntry, PhraseKind } from "./types";

export const phraseCoverage: Record<PhraseKind, PhraseCoverageEntry> = {
  explain: {
    kind: "explain",
    phrase: "explain <symbol|note|repo|project>",
    supportLevel: "supported",
    previewRequired: false,
    behavior: "Resolves a symbol, note, repo, or workspace and opens existing context/detail surfaces.",
    limits: ["Knowledge-card richness is completed by the P1 knowledge-card task."],
  },
  impact: {
    kind: "impact",
    phrase: "impact of <symbol>",
    supportLevel: "supported",
    previewRequired: true,
    behavior: "Resolves a symbol, previews the expensive impact lens, then opens the existing impact graph.",
    limits: ["Full P1 impact envelope metadata arrives in the dedicated impact-lens task."],
  },
  trace_flow: {
    kind: "trace_flow",
    phrase: "trace flow from <symbol>",
    supportLevel: "supported",
    previewRequired: true,
    behavior: "Resolves a symbol, previews execution, then runs the existing flow endpoint.",
    limits: ["Trace table/JSON parity is deferred to the representation task."],
  },
  callers: {
    kind: "callers",
    phrase: "callers of <symbol>",
    supportLevel: "supported",
    previewRequired: false,
    behavior: "Resolves a symbol and focuses the existing related/detail surface for incoming relationships.",
    limits: ["Dedicated caller table parity is deferred to the representation task."],
  },
  callees: {
    kind: "callees",
    phrase: "callees of <symbol>",
    supportLevel: "supported",
    previewRequired: false,
    behavior: "Resolves a symbol and focuses the existing related/detail surface for outgoing relationships.",
    limits: ["Dedicated callee table parity is deferred to the representation task."],
  },
  path: {
    kind: "path",
    phrase: "path from <A> to <B>",
    supportLevel: "supported",
    previewRequired: true,
    behavior: "Resolves both endpoints with candidate recovery and runs the existing path endpoint.",
    limits: ["Path rendering uses the existing pathfinding state until P1 representation parity lands."],
  },
  tests_affected: {
    kind: "tests_affected",
    phrase: "tests affected by <symbol|file>",
    supportLevel: "limited",
    previewRequired: true,
    behavior: "Resolves symbols and routes to impact analysis with explicit limited affected-test metadata.",
    limits: ["There is no P1 frontend affected-tests endpoint yet; confidence is local-only and heuristic."],
  },
  dead_code: {
    kind: "dead_code",
    phrase: "dead code in <repo|project>",
    supportLevel: "limited",
    previewRequired: true,
    behavior: "Uses existing gap analysis as a local-only proxy and labels the result as limited.",
    limits: ["The web UI does not yet expose the full dead_code graph tool."],
  },
  bridges: {
    kind: "bridges",
    phrase: "bridges in <repo|project>",
    supportLevel: "limited",
    previewRequired: true,
    behavior: "Opens scoped overview context and discloses that bridge centrality is not yet a web result set.",
    limits: ["Dedicated bridge ranking/table/JSON parity is deferred."],
  },
  hubs: {
    kind: "hubs",
    phrase: "hubs in <repo|project>",
    supportLevel: "limited",
    previewRequired: true,
    behavior: "Opens scoped overview landmarks as local hub hints.",
    limits: ["Dedicated hub ranking/table/JSON parity is deferred."],
  },
  notes_about: {
    kind: "notes_about",
    phrase: "notes about <topic>",
    supportLevel: "supported",
    previewRequired: false,
    behavior: "Searches note-like results in the active workspace and opens rationale/detail surfaces.",
    limits: ["Unlinked mention expansion is deferred to later rationale work."],
  },
  backlinks: {
    kind: "backlinks",
    phrase: "backlinks for <note>",
    supportLevel: "supported",
    previewRequired: false,
    behavior: "Resolves a note and focuses related detail/backlink surfaces.",
    limits: ["Backlink graph/table/JSON parity is deferred to the representation task."],
  },
  stale_repos: {
    kind: "stale_repos",
    phrase: "stale repos",
    supportLevel: "limited",
    previewRequired: true,
    behavior: "Uses existing repo freshness fields and labels the answer as local workspace freshness.",
    limits: ["Federated/server stale-repo metadata is not wired into the web UI in P1 Task 3."],
  },
  contract_drift: {
    kind: "contract_drift",
    phrase: "contract drift",
    supportLevel: "unsupported",
    previewRequired: true,
    behavior: "Shows an explicit unsupported P1 state instead of pretending contract-drift analysis ran.",
    limits: ["The web UI has no contract_drift route in P1 Task 3."],
  },
};

export const deliberatelyExcludedPhraseBehavior = [
  "Mutating phrases such as delete, reindex, connect upstream, or prune stale sources are excluded from deterministic search phrases.",
  "LLM-only open-ended requests continue through the existing Ask path only after the deterministic parser returns no phrase match.",
];
